<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <IsPackable>false</IsPackable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="Shouldly" Version="4.*" />
    <PackageReference Include="Testably.Abstractions.Testing" Version="3.*" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Shouldly" />
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BWHazel.TopsyTurvy.Analysis\BWHazel.TopsyTurvy.Analysis.csproj" />
    <ProjectReference Include="..\BWHazel.TopsyTurvy.Bindings\BWHazel.TopsyTurvy.Bindings.csproj" />
    <ProjectReference Include="..\BWHazel.TopsyTurvy.Cli\BWHazel.TopsyTurvy.Cli.csproj" />
    <ProjectReference Include="..\BWHazel.TopsyTurvy.Debugger\BWHazel.TopsyTurvy.Debugger.csproj" />
    <ProjectReference Include="..\BWHazel.TopsyTurvy.Embedded\BWHazel.TopsyTurvy.Embedded.csproj" />
    <ProjectReference Include="..\BWHazel.TopsyTurvy.LanguageServer\BWHazel.TopsyTurvy.LanguageServer.csproj" />
    <ProjectReference Include="..\BWHazel.TopsyTurvy.Parser\BWHazel.TopsyTurvy.Parser.csproj" />
    <ProjectReference Include="..\BWHazel.TopsyTurvy.Runtime\BWHazel.TopsyTurvy.Runtime.csproj" />
    <ProjectReference Include="..\BWHazel.TopsyTurvy.Sdk.Interop\BWHazel.TopsyTurvy.Sdk.Interop.csproj" />
    <ProjectReference Include="..\BWHazel.TopsyTurvy.StandardLibrary\BWHazel.TopsyTurvy.StandardLibrary.csproj" />
    <ProjectReference Include="..\BWHazel.TopsyTurvy.Tests.ExternalLibraryFixture\BWHazel.TopsyTurvy.Tests.ExternalLibraryFixture.csproj" />
    <ProjectReference Include="..\BWHazel.TopsyTurvy.TypeChecker\BWHazel.TopsyTurvy.TypeChecker.csproj" />
  </ItemGroup>

</Project>