namespace BWHazel.TopsyTurvy.Analysis;

/// <summary>
/// Provides the canonical set of Topsy Turvy language keywords with descriptive labels.
/// </summary>
/// <remarks>
/// This is the authoritative source of truth for language keywords, their canonical case and their descriptions.
/// The <see cref="Keywords"/> array is the single source of truth for the LSP completion list and the Monaco editor keyword list
/// in the Web Editor and both must stay in sync with this file.  When adding a new language keyword, an entry must be appended
/// here first.
/// </remarks>
public static class KeywordData
{
    /// <summary>
    /// Gets all language keywords and their short descriptions.
    /// </summary>
    public static readonly (string Keyword, string Detail)[] Keywords =
    [
        ("HARK!",                                    "program header"),
        ("or,",                                      "program subtitle"),
        ("FINALE.",                                  "program end"),
        ("TOWN",                                     "namespace declaration"),
        ("WITH DISTRICT",                            "sub-namespace"),
        ("PRINCIPALS",                               "global declarations block"),
        ("THE CURTAIN RISES.",                       "end of declarations"),
        ("PRAY WELCOME",                             "variable declaration"),
        ("AS A",                                     "type annotation"),
        ("BEING",                                    "initial value"),
        ("CONSERVATIVE",                             "constant declaration modifier"),
        ("LIBERAL",                                  "mutable declaration modifier"),
        ("IS APPOINTED",                             "assignment"),
        ("AS IT WERE",                               "expression cast"),
        ("BEHOLD",                                   "print"),
        ("WITHOUT CEREMONY",                         "print (no newline)"),
        ("PRAY TELL",                                "input"),
        ("ASIDE:",                                   "line comment"),
        ("(ASIDE, AT SOME LENGTH:",                  "block comment (open)"),
        ("END OF ASIDE.)",                           "block comment (close)"),
        ("LEGEND:",                                  "documentation comment (summary)"),
        ("RECITATIVE:",                              "documentation comment (remarks)"),
        ("ARTICLE",                                  "documentation comment (parameter)"),
        ("CONSEQUENCE",                              "documentation comment (return value)"),
        ("CURSES",                                   "documentation comment (thrown value)"),
        ("CHORUS:",                                  "documentation comment (code example)"),
        ("ENSEMBLE:",                                "documentation comment (see also)"),
        ("STATUTORY:",                               "documentation comment (deprecation notice)"),
        ("SHOULD IT TRANSPIRE THAT",                 "if condition"),
        ("QUITE SO.",                                "then branch"),
        ("OR, IF NOT,",                              "else-if"),
        ("OTHERWISE,",                               "else branch"),
        ("SO MUCH FOR THAT.",                        "end if"),
        ("IN WHICH CAPACITY?",                       "switch"),
        ("WHEN ACTING AS",                           "case label"),
        ("FAILING ALL OF THE ABOVE,",                "default case"),
        ("NOTHING COULD BE MORE SATISFACTORY.",      "end switch"),
        ("BY A LEGAL FICTION",                       "loop"),
        ("ASCENDING",                                "increment loop variable"),
        ("DESCENDING",                               "decrement loop variable"),
        ("BY",                                       "loop step / transposition shift amount (ASCENDING/DESCENDING ... BY <expr>, TRANSPOSITION UP/DOWN ... BY <expr>)"),
        ("UNTIL",                                    "loop exit condition"),
        ("WHILST",                                   "loop while condition"),
        ("THE TERM EXPIRES.",                        "end loop"),
        ("ONCE MORE.",                               "continue"),
        ("THAT WILL DO.",                            "break (loop or switch)"),
        ("IT IS MY DUTY TO PERFORM",                 "function definition"),
        ("UNDER THE TERMS OF",                       "function parameters"),
        ("UNDER NO OBLIGATION",                      "no-parameter function"),
        ("TO FIND",                                  "function return type"),
        ("AND SO I FIND",                            "return with value"),
        ("MY DUTY IS DISCHARGED.",                   "end function"),
        ("MY DUTY IS PREMATURELY DISCHARGED.",       "return (no value)"),
        ("SUMMON",                                   "function call"),
        ("WITH",                                     "function call arguments"),
        ("WITH DUTY",                                "namespace-qualified function target"),
        ("IF YOU PLEASE.",                           "end expression list"),
        ("A HIDEOUS CURSE ON",                       "throw"),
        ("WITH THE GREATEST RESPECT,",               "try block"),
        ("WITH GRATITUDE",                           "success handler"),
        ("MODIFIED RAPTURE",                         "exception handler"),
        ("THAT CONCLUDES THE MATTER.",               "end try/catch"),
        ("PRAY ADMIT",                               "import"),
        ("PRAY RECOGNISE",                           "open namespace"),
        ("SUM OF",                                   "addition"),
        ("DIFFERENCE OF",                            "subtraction"),
        ("PRODUCT OF",                               "multiplication"),
        ("QUOTIENT OF",                              "division"),
        ("REMAINDER OF",                             "modulo"),
        ("LARGER OF",                                "maximum"),
        ("SMALLER OF",                               "minimum"),
        ("WOVEN OF",                                 "string concatenation"),
        ("BOTH",                                     "logical AND"),
        ("EITHER",                                   "logical OR"),
        ("OR",                                       "logical OR separator (EITHER x OR y)"),
        ("HARDLY EVER",                              "logical NOT"),
        ("ALIKE",                                    "equality (==)"),
        ("UNLIKE",                                   "inequality (!=)"),
        ("PRE-ADAMITE",                              "greater than (>)"),
        ("LOWER DEGREE",                             "less than (<)"),
        ("ALL OF",                                   "all-true (variadic AND)"),
        ("ANY OF",                                   "any-true (variadic OR)"),
        ("CHORD OF",                                 "bitwise AND"),
        ("HARMONY OF",                               "bitwise OR"),
        ("DISCORD OF",                               "bitwise XOR"),
        ("INVERSION OF",                             "bitwise NOT (unary)"),
        ("TRANSPOSITION UP",                         "left shift, defaults to 1 (optional: ... BY <expr>)"),
        ("TRANSPOSITION DOWN",                       "right shift, defaults to 1 (optional: ... BY <expr>)"),
        ("VERITY",                                   "boolean true"),
        ("NAY",                                      "boolean false"),
        ("NAUGHT",                                   "null"),
        ("PEER",                                     "32-bit signed integer type"),
        ("CHANCELLOR",                               "64-bit signed integer type"),
        ("PIRATE",                                   "16-bit signed integer type"),
        ("SAUSAGE-ROLL",                             "8-bit signed integer type"),
        ("STANDING",                                 "unsigned integer modifier"),
        ("FATHOM",                                   "64-bit double-precision float type"),
        ("FOOT",                                     "32-bit single-precision float type"),
        ("YARN",                                     "string type"),
        ("STITCH",                                   "single character type"),
        ("DECREE",                                   "boolean type"),
        ("A LITTLE LIST OF",                         "array type annotation"),
        ("VICTIM",                                   "array element access / assignment"),
        ("ON",                                       "array index separator"),
        ("RECKONING OF",                             "array length expression"),
        ("A GALLERY PICTURE OF",                     "pointer type annotation"),
        ("GALLERY PICTURE TO",                       "address-of / pointer assignment"),
        ("VIEW FROM",                                "pointer dereference"),
        ("YEOMAN",                                   "guard clause"),
        ("UNDER ORDERS.",                            "end guard"),
        ("THE LAW IS",                               "assert statement"),
    ];
}
