using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using BWHazel.TopsyTurvy.Ast;
using BWHazel.TopsyTurvy.UtopIR.Ast;
using BWHazel.TopsyTurvy.UtopIR.Transformer.LabelNameFormatters;
using BWHazel.TopsyTurvy.UtopIR.Transformer.VariableNameFormatters;

namespace BWHazel.TopsyTurvy.UtopIR.Transformer;

/// <summary>
/// Transforms a Topsy Turvy AST (<see cref="ProgramNode"/>) into a flat UtopIR instruction
/// sequence (<see cref="UtopIRProgram"/>).
/// </summary>
/// <remarks>
/// <para>
/// The transformer uses type-switching, consistent with the existing interpreter and
/// type checker in the Topsy Turvy toolchain.
/// </para>
/// <para>
/// Nested expressions such as <c>SUM OF PRODUCT OF a AND b AND c</c> are flattened into
/// a sequence of arithmetic instructions using auto-generated temporary virtual registers.
/// Naming is delegated to an <see cref="ITemporaryVariableNameFormatter"/>, supplied via
/// the constructor, by default an <see cref="IncrementingIntVariableFormatter"/>.
/// </para>
/// <para>
/// ## Widening
/// Mixed-type arithmetic, e.g. <c>SUM OF &lt;peer&gt; AND &lt;chancellor&gt;</c>, is
/// legal in Topsy Turvy.  The result type is the wider of the two operand types, matching the
/// <c>TypeCheckVisitor.Widen</c> ordering, an independent copy, consistent with this project
/// existing pattern of per-layer widening tables.  When an <see cref="ArithmeticInstruction"/>
/// operands would otherwise differ in type, the narrower operand is cast into a temporary register
/// via an inserted <see cref="WereInstruction"/> before the arithmetic instruction is emitted, so
/// every <see cref="ArithmeticInstruction"/> the transformer produces always has matching operand types.
/// </para>
/// <para>
/// ## Scope
/// This implementation covers the instruction set defined in UtopIR v0.0.1-preview3: variable
/// declaration/assignment, integer and floating-point arithmetic operations, bitwise operations,
/// comparison and logical operations, control-flow statements (<c>SHOULD IT TRANSPIRE THAT</c>
/// conditionals, ternary expressions, <c>YEOMAN</c> guard clauses, <c>IN WHICH CAPACITY?</c>
/// switch blocks, all four <c>BY A LEGAL FICTION</c> loop kinds, <c>THAT WILL DO.</c> break and
/// <c>ONCE MORE.</c> continue), and top-level programme return. Control-flow statements are
/// lowered into <c>sail</c>/<c>sailalike</c>/<c>sailunlike</c>/label sequences, with label text
/// generated by an <see cref="ILabelNameFormatter"/> supplied via the constructor, by default a
/// <see cref="InstructionIncrementingDetailLabelNameFormatter"/>. Break and continue targets are resolved via an
/// instance-scoped pair of label stacks rather than being threaded as parameters. Constant
/// inlining, functions and non-numeric types are deferred to later versions.
/// </para>
/// <para>
/// ## Constants
/// Topsy Turvy <c>CONSERVATIVE</c> declarations are currently lowered
/// identically to mutable declarations.  Constant inlining (replacing every reference with
/// its literal value) requires a full symbol-table pass and is deferred.
/// </para>
/// </remarks>
/// <param name="formatter">The formatter used to name temporary virtual registers, or <c>null</c> to use a fresh <see cref="IncrementingIntVariableFormatter"/>.
/// </param>
/// <param name="labelFormatter">The formatter used to name labels, or <c>null</c> to use a fresh <see cref="InstructionIncrementingDetailLabelNameFormatter"/>.
/// </param>
public sealed class TopsyTurvyToUtopIRTransformer(ITemporaryVariableNameFormatter? formatter = null, ILabelNameFormatter? labelFormatter = null)
{
    private readonly ITemporaryVariableNameFormatter formatter = formatter ?? new IncrementingIntVariableFormatter();
    private readonly ILabelNameFormatter labelFormatter = labelFormatter ?? new InstructionIncrementingDetailLabelNameFormatter();

    /// <summary>
    /// The closing label of the innermost enclosing switch or loop, if any, that a <c>THAT WILL
    /// DO.</c> break statement branches to.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Both switch and every loop kind push their own closing label here around their body
    /// transformation, and pop it afterwards, so the top of the stack is always the correct target
    /// for a break at any nesting depth.
    /// </para>
    /// <para>
    /// For example, a switch nested in a loop pushes after the loop, so a break inside the switch
    /// correctly targets the switch, not the loop.
    /// </para>
    /// </remarks>
    private readonly Stack<UtopIRLabel> breakTargets = new();

    /// <summary>
    /// The continue target of the innermost enclosing loop, if any, that a <c>ONCE MORE.</c>
    /// continue statement branches to.
    /// </summary>
    /// <remarks>
    /// Only loop methods push here, never a switch.  A continue inside a switch nested in a
    /// loop must still reach the loop, skipping the switch entirely.
    /// </remarks>
    private readonly Stack<UtopIRLabel> continueTargets = new();

    /// <summary>
    /// Defines the order of numeric <see cref="UtopIRType"/> variants for widening conversions
    /// where index 0 is widest, mirroring <c>TypeCheckVisitor.NumericWideningOrder</c>.
    /// </summary>
    private static readonly UtopIRType[] NumericWideningOrder =
    [
        UtopIRType.Fathom,
        UtopIRType.Foot,
        UtopIRType.StandingChancellor,
        UtopIRType.Chancellor,
        UtopIRType.StandingPeer,
        UtopIRType.Peer,
        UtopIRType.StandingPirate,
        UtopIRType.Pirate,
        UtopIRType.StandingSausageRoll,
        UtopIRType.SausageRoll
    ];

    /// <summary>
    /// Transforms the given Topsy Turvy programme into a <see cref="UtopIRProgram"/>.
    /// </summary>
    /// <param name="program">The root AST node of the Topsy Turvy programme to transform.</param>
    /// <returns>A <see cref="UtopIRProgram"/> containing the equivalent UtopIR instruction sequence.</returns>
    /// <exception cref="NotSupportedException">
    /// Thrown when the programme contains an expression type that is not yet supported by the transformer.
    /// </exception>
    public UtopIRProgram Transform(ProgramNode program)
    {
        List<UtopIRInstruction> instructions = [];
        Dictionary<string, UtopIRType> declaredTypes = [];

        foreach (Statement statement in program.Statements)
        {
            this.TransformStatement(statement, instructions, declaredTypes);
        }

        return new UtopIRProgram(instructions);
    }

    /// <summary>
    /// Dispatches a single top-level or block-level statement for transformation.
    /// </summary>
    /// <param name="statement">The statement to transform.</param>
    /// <param name="instructions">The instruction list being built.</param>
    /// <param name="declaredTypes">The map from variable name to its known <see cref="UtopIRType"/>, used for widening.</param>
    private void TransformStatement(Statement statement, List<UtopIRInstruction> instructions, Dictionary<string, UtopIRType> declaredTypes)
    {
        switch (statement)
        {
            case PrincipalBlockNode principalBlock:
                foreach (Statement declaration in principalBlock.Declarations)
                {
                    this.TransformStatement(declaration, instructions, declaredTypes);
                }

                break;
            case DeclarationNode declaration:
                this.TransformDeclaration(declaration, instructions, declaredTypes);
                break;
            case AssignmentNode assignment:
                this.TransformAssignment(assignment, instructions, declaredTypes);
                break;
            case ProgrammeReturnNode programmeReturn:
                this.TransformProgrammeReturn(programmeReturn, instructions, declaredTypes);
                break;
            case ConditionalNode conditional:
                this.TransformConditional(conditional, instructions, declaredTypes);
                break;
            case GuardNode guard:
                this.TransformGuard(guard, instructions, declaredTypes);
                break;
            case SwitchNode switchNode:
                this.TransformSwitch(switchNode, instructions, declaredTypes);
                break;
            case LoopNode loop:
                this.TransformLoop(loop, instructions, declaredTypes);
                break;
            case BreakNode:
                this.TransformBreak(instructions);
                break;
            case ContinueNode:
                this.TransformContinue(instructions);
                break;
        }
    }

    /// <summary>
    /// Transforms a <see cref="DeclarationNode"/> into a <see cref="WelcomeInstruction"/>
    /// followed by an optional <see cref="AppointInstruction"/> when an initial value is present.
    /// </summary>
    /// <remarks>
    /// When the declared type is an integer type and the initial value inferred type differs (most
    /// commonly because integer literals default to <see cref="UtopIRType.Peer"/>/<see cref="UtopIRType.Chancellor"/>
    /// regardless of the declared target type), a <see cref="WereInstruction"/> cast is inserted via
    /// <see cref="CastOperandIfNeeded"/> so the emitted <see cref="AppointInstruction"/> never stores a
    /// mismatched-width value directly.
    /// </remarks>
    /// <param name="declaration">The declaration statement to transform.</param>
    /// <param name="instructions">The instruction list being built.</param>
    /// <param name="declaredTypes">The map from variable name to its known <see cref="UtopIRType"/>, used for widening.</param>
    private void TransformDeclaration(DeclarationNode declaration, List<UtopIRInstruction> instructions, Dictionary<string, UtopIRType> declaredTypes)
    {
        UtopIRVariable target = new(declaration.Name);
        UtopIRType type = this.MapType(declaration.Type);
        instructions.Add(new WelcomeInstruction(target, type));
        declaredTypes[declaration.Name] = type;

        if (declaration.InitialValue is not null)
        {
            UtopIROperand value = this.TransformExpression(declaration.InitialValue, instructions, declaredTypes);
            if (this.IsCastableType(type))
            {
                UtopIRType valueType = this.InferOperandType(value, declaredTypes);
                value = this.CastOperandIfNeeded(value, valueType, type, instructions, declaredTypes);
            }

            instructions.Add(new AppointInstruction(target, value));
        }
    }

    /// <summary>
    /// Transforms an <see cref="AssignmentNode"/> into an <see cref="AppointInstruction"/>,
    /// flattening the right-hand-side expression first if needed.
    /// </summary>
    /// <remarks>
    /// Casts the value to the target declared type when needed, mirroring <see cref="TransformDeclaration"/>.
    /// The target is already declared by the time an assignment can reference it.
    /// </remarks>
    /// <param name="assignment">The assignment statement to transform.</param>
    /// <param name="instructions">The instruction list being built.</param>
    /// <param name="declaredTypes">The map from variable name to its known <see cref="UtopIRType"/>, used for widening.</param>
    private void TransformAssignment(AssignmentNode assignment, List<UtopIRInstruction> instructions, Dictionary<string, UtopIRType> declaredTypes)
    {
        UtopIRVariable target = new(assignment.Target);
        UtopIROperand value = this.TransformExpression(assignment.Value, instructions, declaredTypes);
        UtopIRType targetType = declaredTypes[assignment.Target];
        if (this.IsCastableType(targetType))
        {
            UtopIRType valueType = this.InferOperandType(value, declaredTypes);
            value = this.CastOperandIfNeeded(value, valueType, targetType, instructions, declaredTypes);
        }

        instructions.Add(new AppointInstruction(target, value));
    }

    /// <summary>
    /// Transforms a <see cref="ProgrammeReturnNode"/> into a <see cref="FindInstruction"/>,
    /// flattening the return-value expression first if needed.
    /// </summary>
    /// <param name="programmeReturn">The programme return statement to transform.</param>
    /// <param name="instructions">The instruction list being built.</param>
    /// <param name="declaredTypes">The map from variable name to its known <see cref="UtopIRType"/>, used for widening.</param>
    private void TransformProgrammeReturn(ProgrammeReturnNode programmeReturn, List<UtopIRInstruction> instructions, Dictionary<string, UtopIRType> declaredTypes)
    {
        UtopIROperand value = this.TransformExpression(programmeReturn.Value, instructions, declaredTypes);
        instructions.Add(new FindInstruction(value));
    }

    /// <summary>
    /// Transforms a <c>THAT WILL DO.</c> break statement into a <see cref="SailInstruction"/>
    /// targeting the closing label of the innermost enclosing switch or loop.
    /// </summary>
    /// <param name="instructions">The instruction list being built.</param>
    /// <exception cref="InvalidOperationException">Thrown when there is no enclosing switch or loop.</exception>
    private void TransformBreak(List<UtopIRInstruction> instructions)
    {
        if (this.breakTargets.Count == 0)
        {
            throw new InvalidOperationException(
                "A THAT WILL DO. break statement was encountered with no enclosing switch or loop block.");
        }

        instructions.Add(new SailInstruction(this.breakTargets.Peek()));
    }

    /// <summary>
    /// Transforms a <c>ONCE MORE.</c> continue statement into a <see cref="SailInstruction"/>
    /// targeting the continue target of the innermost enclosing loop.
    /// </summary>
    /// <param name="instructions">The instruction list being built.</param>
    /// <exception cref="InvalidOperationException">Thrown when there is no enclosing loop.</exception>
    private void TransformContinue(List<UtopIRInstruction> instructions)
    {
        if (this.continueTargets.Count == 0)
        {
            throw new InvalidOperationException(
                "An ONCE MORE. continue statement was encountered with no enclosing loop.");
        }

        instructions.Add(new SailInstruction(this.continueTargets.Peek()));
    }

    /// <summary>
    /// Transforms a <see cref="ConditionalNode"/> into a comparison/branch sequence.
    /// </summary>
    /// <remarks>
    /// <see cref="ConditionalNode.Condition"/> and every <see cref="ElseIfBranch.Condition"/> are
    /// transformed and their comparison/logical instructions emitted, in source order, before any
    /// branch is taken. This differs from <c>Interpreter.ExecuteConditional</c>, which evaluates
    /// lazily and short-circuits at the first true branch.
    /// </remarks>
    /// <param name="node">The conditional statement to transform.</param>
    /// <param name="instructions">The instruction list being built.</param>
    /// <param name="declaredTypes">The map from variable name to its known <see cref="UtopIRType"/>, used for widening.</param>
    private void TransformConditional(ConditionalNode node, List<UtopIRInstruction> instructions, Dictionary<string, UtopIRType> declaredTypes)
    {
        string conditionText = this.BuildConditionText(node.Condition);
        List<string> elseIfConditionTexts = [.. node.ElseIfs.Select(branch => this.BuildConditionText(branch.Condition))];
        ConditionalLabels labels = this.labelFormatter.ForConditional(node, conditionText, elseIfConditionTexts);

        UtopIRLabel closing = labels.ClosingLabel;
        UtopIRLabel trueLabel = labels.TrueLabel;
        IReadOnlyList<UtopIRLabel> elseIfLabels = labels.ElseIfLabels;

        bool hasElse = node.ElseBlock.Count > 0;
        UtopIRLabel elseLabel = labels.ElseLabel;
        UtopIRLabel fallback = hasElse
            ? elseLabel
            : closing;

        UtopIROperand trueOperand = this.TransformExpression(node.Condition, instructions, declaredTypes);
        List<UtopIROperand> elseIfOperands = new(node.ElseIfs.Count);
        foreach (ElseIfBranch branch in node.ElseIfs)
        {
            elseIfOperands.Add(this.TransformExpression(branch.Condition, instructions, declaredTypes));
        }

        instructions.Add(new SailAlikeInstruction(trueOperand, trueLabel));
        for (int i = 0; i < node.ElseIfs.Count; i++)
        {
            instructions.Add(new SailAlikeInstruction(elseIfOperands[i], elseIfLabels[i]));
        }

        instructions.Add(new SailInstruction(fallback));

        instructions.Add(new LabelInstruction(trueLabel));
        foreach (Statement statement in node.TrueBlock)
        {
            this.TransformStatement(statement, instructions, declaredTypes);
        }

        AddClosingSailUnlessUnreachable(instructions, closing);

        for (int i = 0; i < node.ElseIfs.Count; i++)
        {
            instructions.Add(new LabelInstruction(elseIfLabels[i]));
            foreach (Statement statement in node.ElseIfs[i].Block)
            {
                this.TransformStatement(statement, instructions, declaredTypes);
            }

            AddClosingSailUnlessUnreachable(instructions, closing);
        }

        if (hasElse)
        {
            instructions.Add(new LabelInstruction(elseLabel));
            foreach (Statement statement in node.ElseBlock)
            {
                this.TransformStatement(statement, instructions, declaredTypes);
            }
        }

        instructions.Add(new LabelInstruction(closing));
    }

    /// <summary>
    /// Appends an unconditional <c>sail</c> to <paramref name="closing"/>, unless it would be
    /// unreachable.
    /// </summary>
    /// <remarks>
    /// A branch already ending in its own unconditional <c>sail</c> (from a trailing
    /// <c>THAT WILL DO.</c> or <c>ONCE MORE.</c>) makes a further <c>sail</c> to the closing label
    /// dead code, so it is skipped.
    /// </remarks>
    /// <param name="instructions">The instruction list being built.</param>
    /// <param name="closing">The closing label of the construct.</param>
    private static void AddClosingSailUnlessUnreachable(List<UtopIRInstruction> instructions, UtopIRLabel closing)
    {
        if (instructions.Count == 0 || instructions[^1] is not SailInstruction)
        {
            instructions.Add(new SailInstruction(closing));
        }
    }

    /// <summary>
    /// Transforms a <see cref="GuardNode"/> into a comparison/branch sequence.
    /// </summary>
    /// <remarks>
    /// <see cref="GuardNode"/> has no true-branch body of its own: a passing guard has no effect at
    /// all, matching <c>Interpreter.ExecuteGuard</c>.  A <c>sailunlike</c> branches directly to the
    /// else block when the condition is false; when true, an unconditional <c>sail</c> immediately
    /// after skips past it to the closing label.
    /// </remarks>
    /// <param name="node">The guard statement to transform.</param>
    /// <param name="instructions">The instruction list being built.</param>
    /// <param name="declaredTypes">The map from variable name to its known <see cref="UtopIRType"/>, used for widening.</param>
    private void TransformGuard(GuardNode node, List<UtopIRInstruction> instructions, Dictionary<string, UtopIRType> declaredTypes)
    {
        GuardLabels labels = this.labelFormatter.ForGuard(node);
        UtopIRLabel elseLabel = labels.ElseLabel;
        UtopIRLabel closing = labels.ClosingLabel;

        UtopIROperand conditionOperand = this.TransformExpression(node.Condition, instructions, declaredTypes);
        instructions.Add(new SailUnlikeInstruction(conditionOperand, elseLabel));
        instructions.Add(new SailInstruction(closing));

        instructions.Add(new LabelInstruction(elseLabel));
        foreach (Statement statement in node.ElseBlock)
        {
            this.TransformStatement(statement, instructions, declaredTypes);
        }

        instructions.Add(new LabelInstruction(closing));
    }

    /// <summary>
    /// Transforms a <see cref="SwitchNode"/> into a comparison/branch sequence.
    /// </summary>
    /// <remarks>
    /// A <see cref="SwitchCase"/> with an empty <see cref="SwitchCase.Block"/> falls through into
    /// the next case, since no <c>sail</c> is emitted for an empty block.  The closing label is
    /// pushed onto <see cref="breakTargets"/> for the whole transformation, so <c>THAT WILL DO.</c>
    /// inside any case body targets this switch even when nested inside a loop.
    /// </remarks>
    /// <param name="node">The switch statement to transform.</param>
    /// <param name="instructions">The instruction list being built.</param>
    /// <param name="declaredTypes">The map from variable name to its known <see cref="UtopIRType"/>, used for widening.</param>
    private void TransformSwitch(SwitchNode node, List<UtopIRInstruction> instructions, Dictionary<string, UtopIRType> declaredTypes)
    {
        List<string> caseTexts = [.. node.Cases.Select(switchCase => this.SwitchCaseExpressionText(switchCase.Literal))];
        SwitchLabels labels = this.labelFormatter.ForSwitch(node, caseTexts);
        UtopIRLabel closing = labels.ClosingLabel;
        UtopIRLabel defaultLabel = labels.DefaultLabel;
        IReadOnlyList<UtopIRLabel> caseLabels = labels.CaseLabels;
        bool hasDefault = node.DefaultBlock.Count > 0;

        this.breakTargets.Push(closing);
        try
        {
            UtopIROperand switchOperand = this.TransformExpression(node.Expression, instructions, declaredTypes);
            UtopIRType switchType = this.InferOperandType(switchOperand, declaredTypes);

            for (int i = 0; i < node.Cases.Count; i++)
            {
                SwitchCase switchCase = node.Cases[i];
                UtopIRLabel caseLabel = caseLabels[i];

                UtopIROperand compareLeft = switchOperand;
                UtopIROperand compareRight = new LiteralOperand(switchCase.Literal!);
                UtopIRComparisonOperation operation = UtopIRComparisonOperation.Alike;

                if (this.IsCastableType(switchType) && switchCase.Literal is not string)
                {
                    UtopIRType literalType = this.InferOperandType(compareRight, declaredTypes);
                    UtopIRType widenedType = this.Widen(switchType, literalType);
                    compareLeft = this.CastOperandIfNeeded(compareLeft, switchType, widenedType, instructions, declaredTypes);
                    compareRight = this.CastOperandIfNeeded(compareRight, literalType, widenedType, instructions, declaredTypes);
                    if (this.IsFloatType(widenedType))
                    {
                        operation = UtopIRComparisonOperation.AlikeFloat;
                    }
                }

                string mnemonic = this.ComparisonOperationMnemonic(operation);
                string temporaryVariableName = this.formatter.CreateName(mnemonic, this.OperandName(compareLeft), this.OperandName(compareRight));
                UtopIRVariable temporaryVariable = new(temporaryVariableName);
                instructions.Add(new ComparisonInstruction(operation, temporaryVariable, compareLeft, compareRight));
                declaredTypes[temporaryVariableName] = UtopIRType.Decree;

                instructions.Add(new SailAlikeInstruction(new VariableOperand(temporaryVariable), caseLabel));
            }

            instructions.Add(new SailInstruction(hasDefault ? defaultLabel : closing));

            for (int i = 0; i < node.Cases.Count; i++)
            {
                instructions.Add(new LabelInstruction(caseLabels[i]));
                foreach (Statement statement in node.Cases[i].Block)
                {
                    this.TransformStatement(statement, instructions, declaredTypes);
                }
            }

            if (hasDefault)
            {
                instructions.Add(new LabelInstruction(defaultLabel));
                foreach (Statement statement in node.DefaultBlock)
                {
                    this.TransformStatement(statement, instructions, declaredTypes);
                }
            }

            instructions.Add(new LabelInstruction(closing));
        }
        finally
        {
            this.breakTargets.Pop();
        }
    }

    /// <summary>
    /// Dispatches a <see cref="LoopNode"/> to the transform method matching its
    /// <see cref="LoopNode.Type"/>.
    /// </summary>
    /// <param name="node">The loop statement to transform.</param>
    /// <param name="instructions">The instruction list being built.</param>
    /// <param name="declaredTypes">The map from variable name to its known <see cref="UtopIRType"/>, used for widening.</param>
    /// <exception cref="ArgumentOutOfRangeException">Thrown when <see cref="LoopNode.Type"/> is not a recognised <see cref="LoopType"/>.</exception>
    private void TransformLoop(LoopNode node, List<UtopIRInstruction> instructions, Dictionary<string, UtopIRType> declaredTypes)
    {
        switch (node.Type)
        {
            case LoopType.Infinite:
                this.TransformInfiniteLoop(node, instructions, declaredTypes);
                break;
            case LoopType.Whilst:
                this.TransformWhilstLoop(node, instructions, declaredTypes);
                break;
            case LoopType.Ascending:
                this.TransformCountedLoop(node, instructions, declaredTypes, ascending: true);
                break;
            case LoopType.Descending:
                this.TransformCountedLoop(node, instructions, declaredTypes, ascending: false);
                break;
            default:
                throw new ArgumentOutOfRangeException(nameof(node), node.Type, "Unknown loop type.");
        }
    }

    /// <summary>
    /// Transforms an infinite (<see cref="LoopType.Infinite"/>) <see cref="LoopNode"/>.
    /// </summary>
    /// <remarks>
    /// No condition exists to check: the loop can only be exited via <c>THAT WILL DO.</c>.  A
    /// continue reuses the opening label directly since there is no per-iteration mechanism, such
    /// as the increment of a counted loop, that a continue must still let run.
    /// </remarks>
    /// <param name="node">The loop statement to transform.</param>
    /// <param name="instructions">The instruction list being built.</param>
    /// <param name="declaredTypes">The map from variable name to its known <see cref="UtopIRType"/>, used for widening.</param>
    private void TransformInfiniteLoop(LoopNode node, List<UtopIRInstruction> instructions, Dictionary<string, UtopIRType> declaredTypes)
    {
        LoopLabels labels = this.labelFormatter.ForLoop(node, conditionText: null);
        UtopIRLabel opening = labels.OpeningLabel;
        UtopIRLabel closing = labels.ClosingLabel;

        this.breakTargets.Push(closing);
        this.continueTargets.Push(labels.ContinueLabel ?? opening);
        try
        {
            instructions.Add(new LabelInstruction(opening));
            foreach (Statement statement in node.Body)
            {
                this.TransformStatement(statement, instructions, declaredTypes);
            }

            instructions.Add(new SailInstruction(opening));
            instructions.Add(new LabelInstruction(closing));
        }
        finally
        {
            this.breakTargets.Pop();
            this.continueTargets.Pop();
        }
    }

    /// <summary>
    /// Transforms a <see cref="LoopType.Whilst"/> <see cref="LoopNode"/>.
    /// </summary>
    /// <remarks>
    /// The opening label is both the condition-check point, checked before every iteration,
    /// including the first, matching <c>Interpreter.ExecuteWhilstLoop</c>, and the continue target.
    /// A continue can safely reuse it directly since a Whilst loop has no per-iteration mechanism,
    /// such as the increment of a counted loop, that a continue must still let run.
    /// </remarks>
    /// <param name="node">The loop statement to transform.</param>
    /// <param name="instructions">The instruction list being built.</param>
    /// <param name="declaredTypes">The map from variable name to its known <see cref="UtopIRType"/>, used for widening.</param>
    private void TransformWhilstLoop(LoopNode node, List<UtopIRInstruction> instructions, Dictionary<string, UtopIRType> declaredTypes)
    {
        LoopLabels labels = this.labelFormatter.ForLoop(node, this.BuildConditionText(node.Condition!));
        UtopIRLabel opening = labels.OpeningLabel;
        UtopIRLabel closing = labels.ClosingLabel;

        this.breakTargets.Push(closing);
        this.continueTargets.Push(labels.ContinueLabel ?? opening);
        try
        {
            instructions.Add(new LabelInstruction(opening));
            UtopIROperand conditionOperand = this.TransformExpression(node.Condition!, instructions, declaredTypes);
            instructions.Add(new SailUnlikeInstruction(conditionOperand, closing));

            foreach (Statement statement in node.Body)
            {
                this.TransformStatement(statement, instructions, declaredTypes);
            }

            instructions.Add(new SailInstruction(opening));
            instructions.Add(new LabelInstruction(closing));
        }
        finally
        {
            this.breakTargets.Pop();
            this.continueTargets.Pop();
        }
    }

    /// <summary>
    /// Transforms a <see cref="LoopType.Ascending"/> or <see cref="LoopType.Descending"/>
    /// <see cref="LoopNode"/>.
    /// </summary>
    /// <remarks>
    /// The condition is checked before every iteration, including the first, exiting via
    /// <c>sailalike</c> if already true. Continue cannot reuse the opening label directly, since
    /// the increment or decrement must still run after a continue (only a break skips it), so
    /// continue instead targets a dedicated label placed after the body but before the step.
    /// <see cref="LoopNode.Step"/> is transformed dynamically each time it is present, otherwise
    /// the default step is a type-matched literal <c>1</c>. <see cref="LoopNode.LoopVariable"/> is
    /// always an already-declared outer variable; the loop itself never declares it.
    /// </remarks>
    /// <param name="node">The loop statement to transform.</param>
    /// <param name="instructions">The instruction list being built.</param>
    /// <param name="declaredTypes">The map from variable name to its known <see cref="UtopIRType"/>, used for widening.</param>
    /// <param name="ascending"><c>true</c> for <see cref="LoopType.Ascending"/> (uses <c>sum</c>), or <c>false</c> for <see cref="LoopType.Descending"/> (uses <c>diff</c>).</param>
    private void TransformCountedLoop(LoopNode node, List<UtopIRInstruction> instructions, Dictionary<string, UtopIRType> declaredTypes, bool ascending)
    {
        LoopLabels labels = this.labelFormatter.ForLoop(node, this.BuildConditionText(node.Condition!));
        UtopIRLabel opening = labels.OpeningLabel;
        UtopIRLabel continueLabel = labels.ContinueLabel!;
        UtopIRLabel closing = labels.ClosingLabel;

        this.breakTargets.Push(closing);
        this.continueTargets.Push(continueLabel);
        try
        {
            instructions.Add(new LabelInstruction(opening));
            UtopIROperand conditionOperand = this.TransformExpression(node.Condition!, instructions, declaredTypes);
            instructions.Add(new SailAlikeInstruction(conditionOperand, closing));

            foreach (Statement statement in node.Body)
            {
                this.TransformStatement(statement, instructions, declaredTypes);
            }

            instructions.Add(new LabelInstruction(continueLabel));
            UtopIRVariable loopVariable = new(node.LoopVariable!);
            UtopIRType loopVariableType = declaredTypes[node.LoopVariable!];

            UtopIROperand stepOperand;
            if (node.Step is not null)
            {
                UtopIROperand rawStep = this.TransformExpression(node.Step, instructions, declaredTypes);
                UtopIRType rawStepType = this.InferOperandType(rawStep, declaredTypes);
                stepOperand = this.CastOperandIfNeeded(rawStep, rawStepType, loopVariableType, instructions, declaredTypes);
            }
            else
            {
                stepOperand = new LiteralOperand(this.CreateOneLiteral(loopVariableType));
            }

            UtopIRArithmeticOperation operation = ascending ? UtopIRArithmeticOperation.Sum : UtopIRArithmeticOperation.Diff;
            string mnemonic = this.OperationMnemonic(operation);
            string temporaryVariableName = this.formatter.CreateName(mnemonic, this.OperandName(new VariableOperand(loopVariable)), this.OperandName(stepOperand));
            UtopIRVariable temporaryVariable = new(temporaryVariableName);
            instructions.Add(new ArithmeticInstruction(operation, temporaryVariable, new VariableOperand(loopVariable), stepOperand));
            declaredTypes[temporaryVariableName] = loopVariableType;
            instructions.Add(new AppointInstruction(loopVariable, new VariableOperand(temporaryVariable)));

            instructions.Add(new SailInstruction(opening));
            instructions.Add(new LabelInstruction(closing));
        }
        finally
        {
            this.breakTargets.Pop();
            this.continueTargets.Pop();
        }
    }

    /// <summary>
    /// Transforms an expression into a <see cref="UtopIROperand"/>, emitting any necessary
    /// intermediate arithmetic instructions first.
    /// </summary>
    /// <param name="expression">The expression to transform.</param>
    /// <param name="instructions">The instruction list being built.</param>
    /// <param name="declaredTypes">The map from variable name to its known <see cref="UtopIRType"/>, used for widening.</param>
    /// <returns>
    /// A <see cref="LiteralOperand"/> for literal nodes, a <see cref="VariableOperand"/> for
    /// identifier nodes or a <see cref="VariableOperand"/> referencing a newly emitted
    /// temporary register for arithmetic expressions.
    /// </returns>
    /// <exception cref="NotSupportedException">Thrown when the expression type is not supported in the current transformer scope.</exception>
    private UtopIROperand TransformExpression(Expression expression, List<UtopIRInstruction> instructions, Dictionary<string, UtopIRType> declaredTypes)
    {
        switch (expression)
        {
            case LiteralNode literal:
                return new LiteralOperand(literal.Value!);
            case IdentifierNode identifier:
                return new VariableOperand(new UtopIRVariable(identifier.Name));
            case PrefixExpressionNode prefix when this.IsArithmeticOperator(prefix.Operator):
                return this.TransformArithmetic(prefix, instructions, declaredTypes);
            case PrefixExpressionNode prefix when this.IsBitwiseOperator(prefix.Operator):
                return this.TransformBitwise(prefix, instructions, declaredTypes);
            case PrefixExpressionNode prefix when this.IsComparisonOperator(prefix.Operator):
                return this.TransformComparison(prefix, instructions, declaredTypes);
            case PrefixExpressionNode prefix when this.IsLogicalOperator(prefix.Operator):
                return this.TransformLogical(prefix, instructions, declaredTypes);
            case ExpressionCastNode cast:
                return this.TransformCast(cast, instructions, declaredTypes);
            case TernaryExpressionNode ternary:
                return this.TransformTernary(ternary, instructions, declaredTypes);
            default:
                throw new NotSupportedException(
                    $"Expression type '{expression.GetType().Name}' with operator " +
                    $"'{(expression is PrefixExpressionNode prefixExpression ? prefixExpression.Operator : "(none)")}' " +
                    $"is not supported by the transformer in this version.");
        }
    }

    /// <summary>
    /// Transforms an arithmetic <see cref="PrefixExpressionNode"/> by recursively flattening
    /// its operands, widening the narrower operand into a temporary register if the operand
    /// types differ, emitting an <see cref="ArithmeticInstruction"/> into a temporary register,
    /// and returning a <see cref="VariableOperand"/> referencing that register.
    /// </summary>
    /// <remarks>
    /// The instruction group is selected by the widened operand type: floating-point operands
    /// produce the <c>.f</c>-suffixed operation variants, all other operands the integer variants.
    /// </remarks>
    /// <param name="prefix">The arithmetic prefix expression to transform.</param>
    /// <param name="instructions">The instruction list being built.</param>
    /// <param name="declaredTypes">The map from variable name to its known <see cref="UtopIRType"/>, used for widening.</param>
    /// <returns>A <see cref="VariableOperand"/> for the temporary register holding the result.</returns>
    private VariableOperand TransformArithmetic(PrefixExpressionNode prefix, List<UtopIRInstruction> instructions, Dictionary<string, UtopIRType> declaredTypes)
    {
        UtopIROperand operand1 = this.TransformExpression(prefix.Arguments[0], instructions, declaredTypes);
        UtopIROperand operand2 = this.TransformExpression(prefix.Arguments[1], instructions, declaredTypes);

        UtopIRType type1 = this.InferOperandType(operand1, declaredTypes);
        UtopIRType type2 = this.InferOperandType(operand2, declaredTypes);
        UtopIRType widenedType = this.Widen(type1, type2);

        operand1 = this.CastOperandIfNeeded(operand1, type1, widenedType, instructions, declaredTypes);
        operand2 = this.CastOperandIfNeeded(operand2, type2, widenedType, instructions, declaredTypes);

        UtopIRArithmeticOperation operation = this.MapOperator(prefix.Operator);
        if (this.IsFloatType(widenedType))
        {
            operation = this.ToFloatOperation(operation);
        }

        string mnemonic = this.OperationMnemonic(operation);
        string temporaryVariableName = this.formatter.CreateName(mnemonic, this.OperandName(operand1), this.OperandName(operand2));
        UtopIRVariable temporaryVariable = new(temporaryVariableName);
        instructions.Add(new ArithmeticInstruction(operation, temporaryVariable, operand1, operand2));
        declaredTypes[temporaryVariableName] = widenedType;
        return new VariableOperand(temporaryVariable);
    }

    /// <summary>
    /// Transforms a bitwise <see cref="PrefixExpressionNode"/> by recursively flattening its
    /// operands, emitting a <see cref="BitwiseInstruction"/> or <see cref="InvInstruction"/> into
    /// a temporary register, and returning a <see cref="VariableOperand"/> referencing that register.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The binary operators (<c>CHORD OF</c>, <c>HARMONY OF</c>, <c>DISCORD OF</c>) widen the
    /// narrower operand first.  The unary operators keep the operand type as the result type.
    /// </para>
    /// <para>
    /// The UtopIR <c>transup</c> and <c>transdown</c> instructions always take an explicit shift-amount
    /// second operand.  When the Topsy Turvy source omits its optional <c>BY</c> clause <c>TRANSPOSITION UP x</c>
    /// lowers to <c>transup £x, 1</c> with the literal <c>1</c> boxed to match the shifted value own type,
    /// satisfying the same-type operand rule.  When <c>BY</c> is present, the
    /// real shift-amount expression is transformed and cast to match the shifted value type via
    /// <see cref="CastOperandIfNeeded"/>.
    /// </para>
    /// </remarks>
    /// <param name="prefix">The bitwise prefix expression to transform.</param>
    /// <param name="instructions">The instruction list being built.</param>
    /// <param name="declaredTypes">The map from variable name to its known <see cref="UtopIRType"/>, used for widening.</param>
    /// <returns>A <see cref="VariableOperand"/> for the temporary register holding the result.</returns>
    private VariableOperand TransformBitwise(PrefixExpressionNode prefix, List<UtopIRInstruction> instructions, Dictionary<string, UtopIRType> declaredTypes)
    {
        if (prefix.Operator == Operator.InversionOf)
        {
            UtopIROperand operand = this.TransformExpression(prefix.Arguments[0], instructions, declaredTypes);
            UtopIRType operandType = this.InferOperandType(operand, declaredTypes);

            string invTemporaryName = this.formatter.CreateName(UtopIRKeywords.Instructions.Inv, this.OperandName(operand));
            UtopIRVariable invTemporary = new(invTemporaryName);
            instructions.Add(new InvInstruction(invTemporary, operand));
            declaredTypes[invTemporaryName] = operandType;
            return new VariableOperand(invTemporary);
        }

        if (prefix.Operator is Operator.TranspositionUp or Operator.TranspositionDown)
        {
            UtopIROperand operand = this.TransformExpression(prefix.Arguments[0], instructions, declaredTypes);
            UtopIRType operandType = this.InferOperandType(operand, declaredTypes);

            UtopIROperand shiftAmount;
            if (prefix.Arguments.Count > 1)
            {
                UtopIROperand rawShiftAmount = this.TransformExpression(prefix.Arguments[1], instructions, declaredTypes);
                UtopIRType shiftAmountType = this.InferOperandType(rawShiftAmount, declaredTypes);
                shiftAmount = this.CastOperandIfNeeded(rawShiftAmount, shiftAmountType, operandType, instructions, declaredTypes);
            }
            else
            {
                shiftAmount = new LiteralOperand(this.CreateOneLiteral(operandType));
            }

            UtopIRBitwiseOperation shiftOperation = prefix.Operator == Operator.TranspositionUp
                ? UtopIRBitwiseOperation.TransUp
                : UtopIRBitwiseOperation.TransDown;
            
            string shiftMnemonic = this.BitwiseOperationMnemonic(shiftOperation);

            string shiftTemporaryName = this.formatter.CreateName(shiftMnemonic, this.OperandName(operand), this.OperandName(shiftAmount));
            UtopIRVariable shiftTemporary = new(shiftTemporaryName);
            instructions.Add(new BitwiseInstruction(shiftOperation, shiftTemporary, operand, shiftAmount));
            declaredTypes[shiftTemporaryName] = operandType;
            return new VariableOperand(shiftTemporary);
        }

        UtopIROperand operand1 = this.TransformExpression(prefix.Arguments[0], instructions, declaredTypes);
        UtopIROperand operand2 = this.TransformExpression(prefix.Arguments[1], instructions, declaredTypes);

        UtopIRType type1 = this.InferOperandType(operand1, declaredTypes);
        UtopIRType type2 = this.InferOperandType(operand2, declaredTypes);
        UtopIRType widenedType = this.Widen(type1, type2);

        operand1 = this.CastOperandIfNeeded(operand1, type1, widenedType, instructions, declaredTypes);
        operand2 = this.CastOperandIfNeeded(operand2, type2, widenedType, instructions, declaredTypes);

        UtopIRBitwiseOperation operation = this.MapBitwiseOperator(prefix.Operator);
        string mnemonic = this.BitwiseOperationMnemonic(operation);

        string temporaryVariableName = this.formatter.CreateName(mnemonic, this.OperandName(operand1), this.OperandName(operand2));
        UtopIRVariable temporaryVariable = new(temporaryVariableName);
        instructions.Add(new BitwiseInstruction(operation, temporaryVariable, operand1, operand2));
        declaredTypes[temporaryVariableName] = widenedType;
        return new VariableOperand(temporaryVariable);
    }

    /// <summary>
    /// Transforms a comparison <see cref="PrefixExpressionNode"/> by recursively flattening
    /// its operands, widening the narrower operand into a temporary register if the operand
    /// types differ, emitting a <see cref="ComparisonInstruction"/> into a temporary register,
    /// and returning a <see cref="VariableOperand"/> referencing that register.
    /// </summary>
    /// <remarks>
    /// The instruction group is selected by the widened operand type: floating-point operands
    /// produce the <c>.f</c>-suffixed operation variants, all other operands the integer variants.
    /// The target recorded type is always <see cref="UtopIRType.Decree"/>, not the widened operand type.
    /// </remarks>
    /// <param name="prefix">The comparison prefix expression to transform.</param>
    /// <param name="instructions">The instruction list being built.</param>
    /// <param name="declaredTypes">The map from variable name to its known <see cref="UtopIRType"/>, used for widening.</param>
    /// <returns>A <see cref="VariableOperand"/> for the temporary register holding the <c>decree</c> result.</returns>
    private VariableOperand TransformComparison(PrefixExpressionNode prefix, List<UtopIRInstruction> instructions, Dictionary<string, UtopIRType> declaredTypes)
    {
        UtopIROperand operand1 = this.TransformExpression(prefix.Arguments[0], instructions, declaredTypes);
        UtopIROperand operand2 = this.TransformExpression(prefix.Arguments[1], instructions, declaredTypes);

        UtopIRType type1 = this.InferOperandType(operand1, declaredTypes);
        UtopIRType type2 = this.InferOperandType(operand2, declaredTypes);
        UtopIRType widenedType = this.Widen(type1, type2);

        operand1 = this.CastOperandIfNeeded(operand1, type1, widenedType, instructions, declaredTypes);
        operand2 = this.CastOperandIfNeeded(operand2, type2, widenedType, instructions, declaredTypes);

        UtopIRComparisonOperation operation = this.MapComparisonOperator(prefix.Operator);
        if (this.IsFloatType(widenedType))
        {
            operation = this.ToFloatComparisonOperation(operation);
        }

        string mnemonic = this.ComparisonOperationMnemonic(operation);
        string temporaryVariableName = this.formatter.CreateName(mnemonic, this.OperandName(operand1), this.OperandName(operand2));
        UtopIRVariable temporaryVariable = new(temporaryVariableName);
        instructions.Add(new ComparisonInstruction(operation, temporaryVariable, operand1, operand2));
        declaredTypes[temporaryVariableName] = UtopIRType.Decree;
        return new VariableOperand(temporaryVariable);
    }

    /// <summary>
    /// Transforms a logical <see cref="PrefixExpressionNode"/> by recursively flattening its
    /// operand(s), emitting a <see cref="LogicalInstruction"/> or <see cref="HardlyInstruction"/>
    /// into a temporary register, and returning a <see cref="VariableOperand"/> referencing that
    /// register.
    /// </summary>
    /// <remarks>
    /// Unlike the binary operators of <see cref="TransformBitwise"/>, <c>BOTH</c>/<c>EITHER</c>
    /// operands are not widened: the Topsy Turvy type checking already guarantees both operands are
    /// <c>decree</c> before the transformer sees this node.
    /// </remarks>
    /// <param name="prefix">The logical prefix expression to transform.</param>
    /// <param name="instructions">The instruction list being built.</param>
    /// <param name="declaredTypes">The map from variable name to its known <see cref="UtopIRType"/>, used for widening.</param>
    /// <returns>A <see cref="VariableOperand"/> for the temporary register holding the <c>decree</c> result.</returns>
    private VariableOperand TransformLogical(PrefixExpressionNode prefix, List<UtopIRInstruction> instructions, Dictionary<string, UtopIRType> declaredTypes)
    {
        if (prefix.Operator == Operator.HardlyEver)
        {
            UtopIROperand operand = this.TransformExpression(prefix.Arguments[0], instructions, declaredTypes);

            string hardlyTemporaryName = this.formatter.CreateName(UtopIRKeywords.Instructions.Hardly, this.OperandName(operand));
            UtopIRVariable hardlyTemporary = new(hardlyTemporaryName);
            instructions.Add(new HardlyInstruction(hardlyTemporary, operand));
            declaredTypes[hardlyTemporaryName] = UtopIRType.Decree;
            return new VariableOperand(hardlyTemporary);
        }

        UtopIROperand operand1 = this.TransformExpression(prefix.Arguments[0], instructions, declaredTypes);
        UtopIROperand operand2 = this.TransformExpression(prefix.Arguments[1], instructions, declaredTypes);

        UtopIRLogicalOperation operation = this.MapLogicalOperator(prefix.Operator);
        string mnemonic = this.LogicalOperationMnemonic(operation);

        string temporaryVariableName = this.formatter.CreateName(mnemonic, this.OperandName(operand1), this.OperandName(operand2));
        UtopIRVariable temporaryVariable = new(temporaryVariableName);
        instructions.Add(new LogicalInstruction(operation, temporaryVariable, operand1, operand2));
        declaredTypes[temporaryVariableName] = UtopIRType.Decree;
        return new VariableOperand(temporaryVariable);
    }

    /// <summary>
    /// Transforms an <c>AS IT WERE</c> cast by flattening its source expression,
    /// emitting a <see cref="WereInstruction"/> into a temporary register and
    /// returning a <see cref="VariableOperand"/> referencing that register.
    /// </summary>
    /// <param name="cast">The cast expression to transform.</param>
    /// <param name="instructions">The instruction list being built.</param>
    /// <param name="declaredTypes">The map from variable name to its known <see cref="UtopIRType"/>, used for widening.</param>
    /// <returns>A <see cref="VariableOperand"/> for the temporary register holding the cast value.</returns>
    private VariableOperand TransformCast(ExpressionCastNode cast, List<UtopIRInstruction> instructions, Dictionary<string, UtopIRType> declaredTypes)
    {
        UtopIROperand value = this.TransformExpression(cast.Expression, instructions, declaredTypes);
        UtopIRType targetType = this.MapType(cast.NewType);

        string temporaryVariableName = this.formatter.CreateName(UtopIRKeywords.Instructions.Were, this.OperandName(value), targetType.ToString().ToLowerInvariant());
        UtopIRVariable temporaryVariable = new(temporaryVariableName);
        instructions.Add(new WereInstruction(temporaryVariable, value, targetType));
        declaredTypes[temporaryVariableName] = targetType;
        return new VariableOperand(temporaryVariable);
    }

    /// <summary>
    /// Transforms a <see cref="TernaryExpressionNode"/> into a comparison/branch sequence.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Returns a <see cref="VariableOperand"/> for a fresh temporary register rather than folding
    /// the assignment directly into each branch, so a ternary can appear as a sub-expression
    /// anywhere, not only as the direct value of an assignment or declaration.
    /// </para>
    /// <para>
    /// The shared temporary is declared with <c>welcome</c> before branching, using the widened type of
    /// <see cref="TernaryExpressionNode.TrueValue"/> and <see cref="TernaryExpressionNode.FalseValue"/>
    /// via the non-emitting <see cref="InferExpressionType"/>, since only one branch is ever
    /// actually transformed. This is required because <see cref="AppointInstruction"/> has no
    /// auto-declare fallback and needs its target already declared. The widened type matches the
    /// rule already used by <c>TypeCheckVisitor.InferTernary</c>.
    /// </para>
    /// </remarks>
    /// <param name="ternary">The ternary expression to transform.</param>
    /// <param name="instructions">The instruction list being built.</param>
    /// <param name="declaredTypes">The map from variable name to its known <see cref="UtopIRType"/>, used for widening.</param>
    /// <returns>A <see cref="VariableOperand"/> for the temporary register holding the result.</returns>
    private VariableOperand TransformTernary(TernaryExpressionNode ternary, List<UtopIRInstruction> instructions, Dictionary<string, UtopIRType> declaredTypes)
    {
        ConditionalLabels labels = this.labelFormatter.ForConditional(ternary, this.BuildConditionText(ternary.Condition));
        UtopIRLabel closing = labels.ClosingLabel;
        UtopIRLabel trueLabel = labels.TrueLabel;
        UtopIRLabel elseLabel = labels.ElseLabel;

        UtopIROperand conditionOperand = this.TransformExpression(ternary.Condition, instructions, declaredTypes);

        UtopIRType trueType = this.InferExpressionType(ternary.TrueValue, declaredTypes);
        UtopIRType falseType = this.InferExpressionType(ternary.FalseValue, declaredTypes);
        UtopIRType widenedType = this.Widen(trueType, falseType);

        string conditionOperandName = this.OperandName(conditionOperand).TrimStart('_');
        string sharedTemporaryName = this.formatter.CreateName("ternary", conditionOperandName);
        UtopIRVariable sharedTemporary = new(sharedTemporaryName);
        instructions.Add(new WelcomeInstruction(sharedTemporary, widenedType));
        declaredTypes[sharedTemporaryName] = widenedType;

        instructions.Add(new SailAlikeInstruction(conditionOperand, trueLabel));
        instructions.Add(new SailInstruction(elseLabel));

        instructions.Add(new LabelInstruction(trueLabel));
        UtopIROperand trueValue = this.TransformExpression(ternary.TrueValue, instructions, declaredTypes);
        UtopIRType trueValueType = this.InferOperandType(trueValue, declaredTypes);
        trueValue = this.CastOperandIfNeeded(trueValue, trueValueType, widenedType, instructions, declaredTypes);
        instructions.Add(new AppointInstruction(sharedTemporary, trueValue));
        instructions.Add(new SailInstruction(closing));

        instructions.Add(new LabelInstruction(elseLabel));
        UtopIROperand falseValue = this.TransformExpression(ternary.FalseValue, instructions, declaredTypes);
        UtopIRType falseValueType = this.InferOperandType(falseValue, declaredTypes);
        falseValue = this.CastOperandIfNeeded(falseValue, falseValueType, widenedType, instructions, declaredTypes);
        instructions.Add(new AppointInstruction(sharedTemporary, falseValue));

        instructions.Add(new LabelInstruction(closing));
        return new VariableOperand(sharedTemporary);
    }

    /// <summary>
    /// Casts an operand into a new temporary register via an inserted <see cref="WereInstruction"/>
    /// when its type differs from <paramref name="targetType"/>.
    /// </summary>
    /// <param name="operand">The operand to cast if needed.</param>
    /// <param name="operandType">The operand already-known type.</param>
    /// <param name="targetType">The type the operand must be cast to.</param>
    /// <param name="instructions">The instruction list being built.</param>
    /// <param name="declaredTypes">The map from variable name to its known <see cref="UtopIRType"/>, used for widening.</param>
    /// <returns><paramref name="operand"/> unchanged if already of <paramref name="targetType"/>, otherwise a <see cref="VariableOperand"/> referencing the new temporary register.</returns>
    private UtopIROperand CastOperandIfNeeded(UtopIROperand operand, UtopIRType operandType, UtopIRType targetType, List<UtopIRInstruction> instructions, Dictionary<string, UtopIRType> declaredTypes)
    {
        if (operandType == targetType)
        {
            return operand;
        }

        string temporaryVariableName = this.formatter.CreateName(UtopIRKeywords.Instructions.Were, this.OperandName(operand), targetType.ToString().ToLowerInvariant());
        UtopIRVariable temporaryVariable = new(temporaryVariableName);
        instructions.Add(new WereInstruction(temporaryVariable, operand, targetType));
        declaredTypes[temporaryVariableName] = targetType;
        return new VariableOperand(temporaryVariable);
    }

    /// <summary>
    /// Determines whether the given <see cref="UtopIRType"/> is one of the integer types.
    /// </summary>
    /// <param name="type">The type to test.</param>
    /// <returns><c>true</c> if <paramref name="type"/> is an integer type, otherwise <c>false</c>.</returns>
    private bool IsIntegerType(UtopIRType type) =>
        type is UtopIRType.Chancellor
            or UtopIRType.Peer
            or UtopIRType.Pirate
            or UtopIRType.SausageRoll
            or UtopIRType.StandingChancellor
            or UtopIRType.StandingPeer
            or UtopIRType.StandingPirate
            or UtopIRType.StandingSausageRoll;

    /// <summary>
    /// Determines whether the given <see cref="UtopIRType"/> is one of the floating-point types.
    /// </summary>
    /// <param name="type">The type to test.</param>
    /// <returns><c>true</c> if <paramref name="type"/> is a floating-point type, otherwise <c>false</c>.</returns>
    private bool IsFloatType(UtopIRType type) =>
        type is UtopIRType.Fathom
            or UtopIRType.Foot;

    /// <summary>
    /// Determines whether the given <see cref="UtopIRType"/> supports <c>were</c> casting, so a
    /// mismatched initial or assigned value can be coerced to the declared target type.
    /// </summary>
    /// <param name="type">The type to test.</param>
    /// <returns><c>true</c> if <paramref name="type"/> is an integer, floating-point or character type, otherwise <c>false</c>.</returns>
    private bool IsCastableType(UtopIRType type) =>
        this.IsIntegerType(type)
            || this.IsFloatType(type)
            || type == UtopIRType.Stitch;

    /// <summary>
    /// Returns a short name string for a <see cref="UtopIROperand"/>, used when constructing
    /// temporary variable names.
    /// </summary>
    /// <param name="operand">The operand whose name to extract.</param>
    /// <returns>
    /// For a <see cref="VariableOperand"/>, the variable name (without <c>£</c>).
    /// For a <see cref="LiteralOperand"/>, the invariant-culture string representation of the value.
    /// </returns>
    private string OperandName(UtopIROperand operand) => operand switch
    {
        VariableOperand variable => variable.Variable.Name,
        LiteralOperand literal => Convert.ToString(literal.Value, CultureInfo.InvariantCulture) ?? "0",
        _ => throw new ArgumentOutOfRangeException(nameof(operand), operand, "Unknown operand type.")
    };

    /// <summary>
    /// Infers the <see cref="UtopIRType"/> of a <see cref="UtopIROperand"/>, used to decide whether
    /// arithmetic operands need widening.
    /// </summary>
    /// <param name="operand">The operand to infer a type for.</param>
    /// <param name="declaredTypes">The map from variable name to its already-known <see cref="UtopIRType"/>.</param>
    /// <returns>
    /// For a <see cref="VariableOperand"/>, the already-recorded type of the referenced variable.
    /// For a <see cref="LiteralOperand"/>, the type inferred from the literal own CLR runtime type.
    /// </returns>
    /// <exception cref="NotSupportedException">Thrown when a <see cref="LiteralOperand"/> CLR runtime type has no corresponding <see cref="UtopIRType"/> in this version.</exception>
    private UtopIRType InferOperandType(UtopIROperand operand, Dictionary<string, UtopIRType> declaredTypes) => operand switch
    {
        VariableOperand variableOperand => declaredTypes[variableOperand.Variable.Name],
        LiteralOperand literalOperand => literalOperand.Value switch
        {
            long => UtopIRType.Chancellor,
            int => UtopIRType.Peer,
            short => UtopIRType.Pirate,
            sbyte => UtopIRType.SausageRoll,
            ulong => UtopIRType.StandingChancellor,
            uint => UtopIRType.StandingPeer,
            ushort => UtopIRType.StandingPirate,
            byte => UtopIRType.StandingSausageRoll,
            double => UtopIRType.Fathom,
            float => UtopIRType.Foot,
            char => UtopIRType.Stitch,
            bool => UtopIRType.Decree,
            _ => throw new NotSupportedException($"Literal value of CLR type '{literalOperand.Value.GetType().Name}' has no corresponding UtopIR type in this version.")
        },
        _ => throw new NotSupportedException($"Operand type '{operand.GetType().Name}' is not supported.")
    };

    /// <summary>
    /// Returns the wider of two numeric <see cref="UtopIRType"/> variants, according to widening rules.
    /// </summary>
    /// <param name="a">The first numeric type.</param>
    /// <param name="b">The second numeric type.</param>
    /// <returns>The wider of the two types.</returns>
    private UtopIRType Widen(UtopIRType a, UtopIRType b) =>
        this.IndexOfNumericWidening(a) <= this.IndexOfNumericWidening(b)
            ? a
            : b;

    /// <summary>
    /// Gets the index of a <see cref="UtopIRType"/> in <see cref="NumericWideningOrder"/>.
    /// </summary>
    /// <param name="type">The numeric type.</param>
    /// <returns>The index of the type in the widening order, or <see cref="int.MaxValue"/> if not found.</returns>
    private int IndexOfNumericWidening(UtopIRType type)
    {
        for (int i = 0; i < NumericWideningOrder.Length; i++)
        {
            if (NumericWideningOrder[i] == type)
            {
                return i;
            }
        }

        return int.MaxValue;
    }

    /// <summary>
    /// Returns whether the given <see cref="Operator"/> is one of the arithmetic operators
    /// supported by the transformer.
    /// </summary>
    /// <param name="theOperator">The operator to test.</param>
    /// <returns><c>true</c> if the operator maps to a <see cref="UtopIRArithmeticOperation"/>, otherwise <c>false</c>.</returns>
    private bool IsArithmeticOperator(Operator theOperator) =>
        theOperator is Operator.Sum
            or Operator.Difference
            or Operator.Product
            or Operator.Quotient
            or Operator.Remainder
            or Operator.Larger
            or Operator.Smaller;

    /// <summary>
    /// Determines whether the given <see cref="Operator"/> is one of the bitwise operators
    /// supported by the transformer.
    /// </summary>
    /// <param name="theOperator">The operator to test.</param>
    /// <returns><c>true</c> if the operator lowers to a <see cref="BitwiseInstruction"/> or <see cref="InvInstruction"/>, otherwise <c>false</c>.</returns>
    private bool IsBitwiseOperator(Operator theOperator) =>
        theOperator is Operator.ChordOf
            or Operator.HarmonyOf
            or Operator.DiscordOf
            or Operator.InversionOf
            or Operator.TranspositionUp
            or Operator.TranspositionDown;

    /// <summary>
    /// Returns whether the given <see cref="Operator"/> is one of the comparison operators
    /// supported by the transformer.
    /// </summary>
    /// <param name="theOperator">The operator to test.</param>
    /// <returns><c>true</c> if the operator maps to a <see cref="UtopIRComparisonOperation"/>, otherwise <c>false</c>.</returns>
    private bool IsComparisonOperator(Operator theOperator) =>
        theOperator is Operator.Alike
            or Operator.Unlike
            or Operator.PreAdamite
            or Operator.LowerDegree;

    /// <summary>
    /// Returns whether the given <see cref="Operator"/> is one of the logical operators
    /// supported by the transformer.
    /// </summary>
    /// <param name="theOperator">The operator to test.</param>
    /// <returns><c>true</c> if the operator lowers to a <see cref="LogicalInstruction"/> or <see cref="HardlyInstruction"/>, otherwise <c>false</c>.</returns>
    private bool IsLogicalOperator(Operator theOperator) =>
        theOperator is Operator.Both
            or Operator.Either
            or Operator.HardlyEver;

    /// <summary>
    /// Maps a binary bitwise Topsy Turvy <see cref="Operator"/> to the corresponding
    /// <see cref="UtopIRBitwiseOperation"/>.
    /// </summary>
    /// <param name="theOperator">The Topsy Turvy operator to map.</param>
    /// <returns>The corresponding <see cref="UtopIRBitwiseOperation"/>.</returns>
    /// <exception cref="ArgumentOutOfRangeException">Thrown when <paramref name="theOperator"/> is not a binary bitwise operator.</exception>
    private UtopIRBitwiseOperation MapBitwiseOperator(Operator theOperator) => theOperator switch
    {
        Operator.ChordOf => UtopIRBitwiseOperation.Chord,
        Operator.HarmonyOf => UtopIRBitwiseOperation.Harmony,
        Operator.DiscordOf => UtopIRBitwiseOperation.Discord,
        _ => throw new ArgumentOutOfRangeException(nameof(theOperator), theOperator, "Operator is not a binary bitwise operator.")
    };

    /// <summary>
    /// Returns the UtopIR mnemonic string for the given <see cref="UtopIRBitwiseOperation"/>.
    /// </summary>
    /// <param name="operation">The bitwise operation.</param>
    /// <returns>The mnemonic string.</returns>
    private string BitwiseOperationMnemonic(UtopIRBitwiseOperation operation) => operation switch
    {
        UtopIRBitwiseOperation.Chord => UtopIRKeywords.Instructions.Chord,
        UtopIRBitwiseOperation.Harmony => UtopIRKeywords.Instructions.Harmony,
        UtopIRBitwiseOperation.Discord => UtopIRKeywords.Instructions.Discord,
        UtopIRBitwiseOperation.TransUp => UtopIRKeywords.Instructions.TransUp,
        UtopIRBitwiseOperation.TransDown => UtopIRKeywords.Instructions.TransDown,
        _ => throw new ArgumentOutOfRangeException(nameof(operation), operation, "Unknown bitwise operation.")
    };

    /// <summary>
    /// Returns the literal value <c>1</c> boxed as the CLR type corresponding to the given integer
    /// <see cref="UtopIRType"/>, used as the shift amount when lowering transposition operators.
    /// </summary>
    /// <param name="type">The integer type the literal must match.</param>
    /// <returns>The value <c>1</c> boxed as the matching CLR type.</returns>
    /// <exception cref="ArgumentOutOfRangeException">Thrown when <paramref name="type"/> is not an integer type.</exception>
    private object CreateOneLiteral(UtopIRType type) => type switch
    {
        UtopIRType.Chancellor => 1L,
        UtopIRType.Peer => 1,
        UtopIRType.Pirate => (short)1,
        UtopIRType.SausageRoll => (sbyte)1,
        UtopIRType.StandingChancellor => 1UL,
        UtopIRType.StandingPeer => 1U,
        UtopIRType.StandingPirate => (ushort)1,
        UtopIRType.StandingSausageRoll => (byte)1,
        _ => throw new ArgumentOutOfRangeException(nameof(type), type, "Shift amounts require an integer type.")
    };

    /// <summary>
    /// Maps a Topsy Turvy <see cref="Operator"/> to the corresponding
    /// <see cref="UtopIRArithmeticOperation"/>.
    /// </summary>
    /// <param name="theOperator">The Topsy Turvy operator to map.</param>
    /// <returns>The corresponding <see cref="UtopIRArithmeticOperation"/>.</returns>
    /// <exception cref="ArgumentOutOfRangeException">Thrown when <paramref name="theOperator"/> is not an arithmetic operator.</exception>
    private UtopIRArithmeticOperation MapOperator(Operator theOperator) => theOperator switch
    {
        Operator.Sum => UtopIRArithmeticOperation.Sum,
        Operator.Difference => UtopIRArithmeticOperation.Diff,
        Operator.Product => UtopIRArithmeticOperation.Prod,
        Operator.Quotient => UtopIRArithmeticOperation.Quot,
        Operator.Remainder => UtopIRArithmeticOperation.Rem,
        Operator.Larger => UtopIRArithmeticOperation.Max,
        Operator.Smaller => UtopIRArithmeticOperation.Min,
        _ => throw new ArgumentOutOfRangeException(nameof(theOperator), theOperator, "Operator is not arithmetic.")
    };

    /// <summary>
    /// Returns the floating-point variant of the given integer <see cref="UtopIRArithmeticOperation"/>.
    /// </summary>
    /// <param name="operation">The integer arithmetic operation.</param>
    /// <returns>The corresponding <c>.f</c>-suffixed <see cref="UtopIRArithmeticOperation"/>.</returns>
    /// <exception cref="ArgumentOutOfRangeException">Thrown when <paramref name="operation"/> is not an integer arithmetic operation.</exception>
    private UtopIRArithmeticOperation ToFloatOperation(UtopIRArithmeticOperation operation) => operation switch
    {
        UtopIRArithmeticOperation.Sum => UtopIRArithmeticOperation.SumFloat,
        UtopIRArithmeticOperation.Diff => UtopIRArithmeticOperation.DiffFloat,
        UtopIRArithmeticOperation.Prod => UtopIRArithmeticOperation.ProdFloat,
        UtopIRArithmeticOperation.Quot => UtopIRArithmeticOperation.QuotFloat,
        UtopIRArithmeticOperation.Rem => UtopIRArithmeticOperation.RemFloat,
        UtopIRArithmeticOperation.Max => UtopIRArithmeticOperation.MaxFloat,
        UtopIRArithmeticOperation.Min => UtopIRArithmeticOperation.MinFloat,
        _ => throw new ArgumentOutOfRangeException(nameof(operation), operation, "Operation has no floating-point variant.")
    };

    /// <summary>
    /// Returns the UtopIR mnemonic string for the given <see cref="UtopIRArithmeticOperation"/>.
    /// </summary>
    /// <param name="operation">The arithmetic operation.</param>
    /// <returns>The mnemonic string.</returns>
    private string OperationMnemonic(UtopIRArithmeticOperation operation) => operation switch
    {
        UtopIRArithmeticOperation.Sum => UtopIRKeywords.Instructions.Sum,
        UtopIRArithmeticOperation.Diff => UtopIRKeywords.Instructions.Diff,
        UtopIRArithmeticOperation.Prod => UtopIRKeywords.Instructions.Prod,
        UtopIRArithmeticOperation.Quot => UtopIRKeywords.Instructions.Quot,
        UtopIRArithmeticOperation.Rem => UtopIRKeywords.Instructions.Rem,
        UtopIRArithmeticOperation.Max => UtopIRKeywords.Instructions.Max,
        UtopIRArithmeticOperation.Min => UtopIRKeywords.Instructions.Min,
        UtopIRArithmeticOperation.SumFloat => UtopIRKeywords.Instructions.SumFloat,
        UtopIRArithmeticOperation.DiffFloat => UtopIRKeywords.Instructions.DiffFloat,
        UtopIRArithmeticOperation.ProdFloat => UtopIRKeywords.Instructions.ProdFloat,
        UtopIRArithmeticOperation.QuotFloat => UtopIRKeywords.Instructions.QuotFloat,
        UtopIRArithmeticOperation.RemFloat => UtopIRKeywords.Instructions.RemFloat,
        UtopIRArithmeticOperation.MaxFloat => UtopIRKeywords.Instructions.MaxFloat,
        UtopIRArithmeticOperation.MinFloat => UtopIRKeywords.Instructions.MinFloat,
        _ => throw new ArgumentOutOfRangeException(nameof(operation), operation, "Unknown arithmetic operation.")
    };

    /// <summary>
    /// Maps a Topsy Turvy <see cref="Operator"/> to the corresponding
    /// <see cref="UtopIRComparisonOperation"/>.
    /// </summary>
    /// <param name="theOperator">The Topsy Turvy operator to map.</param>
    /// <returns>The corresponding <see cref="UtopIRComparisonOperation"/>.</returns>
    /// <exception cref="ArgumentOutOfRangeException">Thrown when <paramref name="theOperator"/> is not a comparison operator.</exception>
    private UtopIRComparisonOperation MapComparisonOperator(Operator theOperator) => theOperator switch
    {
        Operator.Alike => UtopIRComparisonOperation.Alike,
        Operator.Unlike => UtopIRComparisonOperation.Unlike,
        Operator.PreAdamite => UtopIRComparisonOperation.PreAdam,
        Operator.LowerDegree => UtopIRComparisonOperation.LowerDeg,
        _ => throw new ArgumentOutOfRangeException(nameof(theOperator), theOperator, "Operator is not a comparison operator.")
    };

    /// <summary>
    /// Returns the floating-point variant of the given integer <see cref="UtopIRComparisonOperation"/>.
    /// </summary>
    /// <param name="operation">The integer comparison operation.</param>
    /// <returns>The corresponding <c>.f</c>-suffixed <see cref="UtopIRComparisonOperation"/>.</returns>
    /// <exception cref="ArgumentOutOfRangeException">Thrown when <paramref name="operation"/> is not an integer comparison operation.</exception>
    private UtopIRComparisonOperation ToFloatComparisonOperation(UtopIRComparisonOperation operation) => operation switch
    {
        UtopIRComparisonOperation.Alike => UtopIRComparisonOperation.AlikeFloat,
        UtopIRComparisonOperation.Unlike => UtopIRComparisonOperation.UnlikeFloat,
        UtopIRComparisonOperation.PreAdam => UtopIRComparisonOperation.PreAdamFloat,
        UtopIRComparisonOperation.LowerDeg => UtopIRComparisonOperation.LowerDegFloat,
        _ => throw new ArgumentOutOfRangeException(nameof(operation), operation, "Operation has no floating-point variant.")
    };

    /// <summary>
    /// Returns the UtopIR mnemonic string for the given <see cref="UtopIRComparisonOperation"/>.
    /// </summary>
    /// <param name="operation">The comparison operation.</param>
    /// <returns>The mnemonic string.</returns>
    private string ComparisonOperationMnemonic(UtopIRComparisonOperation operation) => operation switch
    {
        UtopIRComparisonOperation.Alike => UtopIRKeywords.Instructions.Alike,
        UtopIRComparisonOperation.Unlike => UtopIRKeywords.Instructions.Unlike,
        UtopIRComparisonOperation.PreAdam => UtopIRKeywords.Instructions.PreAdam,
        UtopIRComparisonOperation.LowerDeg => UtopIRKeywords.Instructions.LowerDeg,
        UtopIRComparisonOperation.AlikeFloat => UtopIRKeywords.Instructions.AlikeFloat,
        UtopIRComparisonOperation.UnlikeFloat => UtopIRKeywords.Instructions.UnlikeFloat,
        UtopIRComparisonOperation.PreAdamFloat => UtopIRKeywords.Instructions.PreAdamFloat,
        UtopIRComparisonOperation.LowerDegFloat => UtopIRKeywords.Instructions.LowerDegFloat,
        _ => throw new ArgumentOutOfRangeException(nameof(operation), operation, "Unknown comparison operation.")
    };

    /// <summary>
    /// Maps a binary logical Topsy Turvy <see cref="Operator"/> to the corresponding
    /// <see cref="UtopIRLogicalOperation"/>.
    /// </summary>
    /// <param name="theOperator">The Topsy Turvy operator to map.</param>
    /// <returns>The corresponding <see cref="UtopIRLogicalOperation"/>.</returns>
    /// <exception cref="ArgumentOutOfRangeException">Thrown when <paramref name="theOperator"/> is not a binary logical operator.</exception>
    private UtopIRLogicalOperation MapLogicalOperator(Operator theOperator) => theOperator switch
    {
        Operator.Both => UtopIRLogicalOperation.Both,
        Operator.Either => UtopIRLogicalOperation.Either,
        _ => throw new ArgumentOutOfRangeException(nameof(theOperator), theOperator, "Operator is not a binary logical operator.")
    };

    /// <summary>
    /// Returns the UtopIR mnemonic string for the given <see cref="UtopIRLogicalOperation"/>.
    /// </summary>
    /// <param name="operation">The logical operation.</param>
    /// <returns>The mnemonic string.</returns>
    private string LogicalOperationMnemonic(UtopIRLogicalOperation operation) => operation switch
    {
        UtopIRLogicalOperation.Both => UtopIRKeywords.Instructions.Both,
        UtopIRLogicalOperation.Either => UtopIRKeywords.Instructions.Either,
        _ => throw new ArgumentOutOfRangeException(nameof(operation), operation, "Unknown logical operation.")
    };

    /// <summary>
    /// Maps a Topsy Turvy <see cref="LiteralType"/> to the corresponding <see cref="UtopIRType"/>.
    /// </summary>
    /// <param name="type">The Topsy Turvy literal type to map.</param>
    /// <returns>The corresponding <see cref="UtopIRType"/>.</returns>
    /// <exception cref="ArgumentOutOfRangeException">Thrown when <paramref name="type"/> has no UtopIR equivalent.</exception>
    private UtopIRType MapType(LiteralType type) => type switch
    {
        LiteralType.Integer => UtopIRType.Peer,
        LiteralType.Long => UtopIRType.Chancellor,
        LiteralType.Short => UtopIRType.Pirate,
        LiteralType.SignedByte => UtopIRType.SausageRoll,
        LiteralType.UnsignedInteger => UtopIRType.StandingPeer,
        LiteralType.UnsignedLong => UtopIRType.StandingChancellor,
        LiteralType.UnsignedShort => UtopIRType.StandingPirate,
        LiteralType.Byte => UtopIRType.StandingSausageRoll,
        LiteralType.Double => UtopIRType.Fathom,
        LiteralType.Single => UtopIRType.Foot,
        LiteralType.Boolean => UtopIRType.Decree,
        LiteralType.Char => UtopIRType.Stitch,
        LiteralType.String => UtopIRType.Yarn,
        _ => throw new ArgumentOutOfRangeException(nameof(type), type, $"LiteralType '{type}' has no UtopIR equivalent.")
    };

    /// <summary>
    /// Builds label text describing an expression, without emitting any instructions.
    /// </summary>
    /// <remarks>
    /// A construct label needs its text before the real instructions for the expression are emitted, so
    /// this walks the expression tree directly instead of reading from already-emitted
    /// instructions.
    /// </remarks>
    /// <param name="expression">The expression to build label text for.</param>
    /// <returns>The formatted label text.</returns>
    /// <exception cref="NotSupportedException">Thrown when the expression type has no label text representation.</exception>
    private string BuildConditionText(Expression expression) => expression switch
    {
        LiteralNode literal => this.labelFormatter.FormatText(this.OperandName(new LiteralOperand(literal.Value!))),
        IdentifierNode identifier => this.labelFormatter.FormatText(identifier.Name),
        PrefixExpressionNode prefix when prefix.Arguments.Count == 1 =>
            this.labelFormatter.FormatText(this.MnemonicForOperator(prefix.Operator), this.RawOperandText(prefix.Arguments[0])),
        PrefixExpressionNode prefix =>
            this.labelFormatter.FormatText(this.MnemonicForOperator(prefix.Operator), this.RawOperandText(prefix.Arguments[0]), this.RawOperandText(prefix.Arguments[1])),
        ExpressionCastNode cast => this.BuildConditionText(cast.Expression),
        _ => throw new NotSupportedException($"Expression type '{expression.GetType().Name}' has no label text representation.")
    };

    /// <summary>
    /// Returns the unformatted text for a single operand of a <see cref="PrefixExpressionNode"/>,
    /// used by <see cref="BuildConditionText"/>.
    /// </summary>
    /// <param name="expression">The operand expression.</param>
    /// <returns>
    /// For a <see cref="LiteralNode"/>, its raw value text. For an <see cref="IdentifierNode"/>,
    /// its name. For a nested <see cref="PrefixExpressionNode"/>, the text from a recursive
    /// <see cref="BuildConditionText"/> call.
    /// </returns>
    /// <exception cref="NotSupportedException">Thrown when the expression type cannot be used as a label operand.</exception>
    private string RawOperandText(Expression expression) => expression switch
    {
        LiteralNode literal => this.OperandName(new LiteralOperand(literal.Value!)),
        IdentifierNode identifier => identifier.Name,
        PrefixExpressionNode nested => this.BuildConditionText(nested),
        ExpressionCastNode cast => this.RawOperandText(cast.Expression),
        _ => throw new NotSupportedException($"Expression type '{expression.GetType().Name}' cannot be used as a label operand.")
    };

    /// <summary>
    /// Returns the plain (non-<c>.f</c>) UtopIR mnemonic for an operator, used to build label text.
    /// </summary>
    /// <param name="theOperator">The operator to map.</param>
    /// <returns>The plain UtopIR mnemonic string.</returns>
    /// <exception cref="NotSupportedException">Thrown when <paramref name="theOperator"/> has no label mnemonic.</exception>
    private string MnemonicForOperator(Operator theOperator)
    {
        if (this.IsArithmeticOperator(theOperator))
        {
            return this.OperationMnemonic(this.MapOperator(theOperator));
        }

        if (theOperator == Operator.InversionOf)
        {
            return UtopIRKeywords.Instructions.Inv;
        }

        if (theOperator is Operator.TranspositionUp or Operator.TranspositionDown)
        {
            return this.BitwiseOperationMnemonic(theOperator == Operator.TranspositionUp
                ? UtopIRBitwiseOperation.TransUp
                : UtopIRBitwiseOperation.TransDown);
        }

        if (this.IsBitwiseOperator(theOperator))
        {
            return this.BitwiseOperationMnemonic(this.MapBitwiseOperator(theOperator));
        }

        if (this.IsComparisonOperator(theOperator))
        {
            return this.ComparisonOperationMnemonic(this.MapComparisonOperator(theOperator));
        }

        if (theOperator == Operator.HardlyEver)
        {
            return UtopIRKeywords.Instructions.Hardly;
        }

        if (this.IsLogicalOperator(theOperator))
        {
            return this.LogicalOperationMnemonic(this.MapLogicalOperator(theOperator));
        }

        throw new NotSupportedException($"Operator '{theOperator}' has no label mnemonic.");
    }

    /// <summary>
    /// Builds label text for the literal value of a switch case.
    /// </summary>
    /// <param name="literal">The raw case literal value.</param>
    /// <returns>The formatted label text.</returns>
    private string SwitchCaseExpressionText(object? literal) =>
        this.labelFormatter.FormatText(literal is null ? "0" : this.OperandName(new LiteralOperand(literal)));

    /// <summary>
    /// Infers the <see cref="UtopIRType"/> an expression would produce if transformed, without
    /// emitting any instructions.
    /// </summary>
    /// <remarks>
    /// Needed by ternary lowering: the type of both branches must be known before the shared
    /// temporary register is declared with <c>welcome</c> but only one branch is ever actually transformed.
    /// </remarks>
    /// <param name="expression">The expression to infer a type for.</param>
    /// <param name="declaredTypes">The map from variable name to its known <see cref="UtopIRType"/>.</param>
    /// <returns>The <see cref="UtopIRType"/> the expression would produce.</returns>
    /// <exception cref="NotSupportedException">Thrown when the expression type has no inferable type.</exception>
    private UtopIRType InferExpressionType(Expression expression, Dictionary<string, UtopIRType> declaredTypes) => expression switch
    {
        LiteralNode literal => this.InferOperandType(new LiteralOperand(literal.Value!), declaredTypes),
        IdentifierNode identifier => declaredTypes[identifier.Name],
        PrefixExpressionNode prefix when prefix.Operator == Operator.InversionOf => this.InferExpressionType(prefix.Arguments[0], declaredTypes),
        PrefixExpressionNode prefix when prefix.Operator is Operator.TranspositionUp or Operator.TranspositionDown => this.InferExpressionType(prefix.Arguments[0], declaredTypes),
        PrefixExpressionNode prefix when this.IsComparisonOperator(prefix.Operator) || this.IsLogicalOperator(prefix.Operator) => UtopIRType.Decree,
        PrefixExpressionNode prefix when this.IsArithmeticOperator(prefix.Operator) || this.IsBitwiseOperator(prefix.Operator) => this.Widen(this.InferExpressionType(prefix.Arguments[0], declaredTypes), this.InferExpressionType(prefix.Arguments[1], declaredTypes)),
        ExpressionCastNode cast => this.MapType(cast.NewType),
        _ => throw new NotSupportedException($"Expression type '{expression.GetType().Name}' has no inferable type.")
    };
}
