import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Language Guide',
      link: {type: 'doc', id: 'guide/index'},
      items: [],
    },
  ],
  tutorialsSidebar: [
    {
      type: 'category',
      label: 'Tutorials',
      link: {type: 'doc', id: 'tutorials/index'},
      items: [],
    },
  ],
  conceptsSidebar: [
    {
      type: 'category',
      label: 'Concepts',
      link: {type: 'doc', id: 'concepts/index'},
      items: [],
    },
  ],
  apiSidebar: [
    {
      type: 'category',
      label: 'API Reference',
      link: {type: 'doc', id: 'api/index'},
      items: [
        {type: 'autogenerated', dirName: 'api/dotnet'},
      ],
    },
  ],
};

export default sidebars;
