import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  gettingStartedSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      link: {type: 'doc', id: 'start/index'},
      items: [
        {type: 'doc', id: 'start/installation'},
        {type: 'doc', id: 'start/quick-start'},
        {
          type: 'category',
          label: 'Releases',
          link: {type: 'doc', id: 'start/releases/index'},
          items: [
            {type: 'doc', id: 'start/releases/2025-06-19'},
          ],
        },
      ],
    },
  ],
  docsSidebar: [
    {
      type: 'category',
      label: 'Language Guide',
      link: {type: 'doc', id: 'guide/index'},
      items: [],
    },
  ],
  tutorialsSidebar: [
    {
      type: 'category',
      label: 'Tutorials',
      link: {type: 'doc', id: 'tutorials/index'},
      items: [],
    },
  ],
  conceptsSidebar: [
    {
      type: 'category',
      label: 'Concepts',
      link: {type: 'doc', id: 'concepts/index'},
      items: [
        {type: 'doc', id: 'concepts/grammar'},
        {type: 'doc', id: 'concepts/pre-processor'},
        {type: 'doc', id: 'concepts/parser'},
        {type: 'doc', id: 'concepts/ast'},
        {type: 'doc', id: 'concepts/runtime'},
        {type: 'doc', id: 'concepts/analysis'},
        {type: 'doc', id: 'concepts/language-server'},
      ],
    },
  ],
  apiSidebar: [
    {
      type: 'category',
      label: 'API Reference',
      link: {type: 'doc', id: 'api/index'},
      items: [
        {type: 'autogenerated', dirName: 'api/dotnet'},
      ],
    },
  ],
};

export default sidebars;
