namespace BWHazel.TopsyTurvy.Analysis;

/// <summary>
/// Provides the canonical set of Topsy Turvy language keywords with descriptive labels.
/// </summary>
/// <remarks>
/// This is the authoritative source of truth for language keywords, their canonical case and their descriptions.
/// </remarks>
public static class KeywordData
{
    /// <summary>
    /// Gets all language keywords and their short descriptions.
    /// </summary>
    public static readonly (string Keyword, string Detail)[] Keywords =
    [
        ("HARK!",                                    "program header"),
        ("or,",                                      "program subtitle"),
        ("FINALE.",                                  "program end"),
        ("PRINCIPALS",                               "global declarations block"),
        ("THE CURTAIN RISES.",                       "end of declarations"),
        ("PRAY WELCOME",                             "variable declaration"),
        ("AS A",                                     "type annotation"),
        ("BEING",                                    "initial value"),
        ("CONSERVATIVE",                             "constant declaration modifier"),
        ("LIBERAL",                                  "mutable declaration modifier"),
        ("IS APPOINTED",                             "assignment"),
        ("IS HENCEFORTH A",                          "in-place cast"),
        ("AS IT WERE",                               "expression cast"),
        ("BEHOLD",                                   "print"),
        ("WITHOUT CEREMONY",                         "print (no newline)"),
        ("PRAY TELL",                                "input"),
        ("ASIDE:",                                   "line comment"),
        ("(ASIDE, AT SOME LENGTH:",                  "block comment (open)"),
        ("END OF ASIDE.)",                           "block comment (close)"),
        ("SHOULD IT TRANSPIRE THAT",                 "if condition"),
        ("QUITE SO.",                                "then branch"),
        ("OR, IF NOT,",                              "else-if"),
        ("OTHERWISE,",                               "else branch"),
        ("SO MUCH FOR THAT.",                        "end if"),
        ("IN WHICH CAPACITY?",                       "switch"),
        ("WHEN ACTING AS",                           "case label"),
        ("FAILING ALL OF THE ABOVE,",                "default case"),
        ("NOTHING COULD BE MORE SATISFACTORY.",      "end switch"),
        ("BY A LEGAL FICTION",                       "loop"),
        ("ASCENDING",                                "increment loop variable"),
        ("DESCENDING",                               "decrement loop variable"),
        ("UNTIL",                                    "loop exit condition"),
        ("WHILST",                                   "loop while condition"),
        ("THE TERM EXPIRES.",                        "end loop"),
        ("ONCE MORE.",                               "continue"),
        ("THAT WILL DO.",                            "break (loop or switch)"),
        ("IT IS MY DUTY TO PERFORM",                 "function definition"),
        ("UNDER THE TERMS OF",                       "function parameters"),
        ("UNDER NO OBLIGATION",                      "no-parameter function"),
        ("AND SO I FIND",                            "return with value"),
        ("MY DUTY IS DISCHARGED.",                   "end function"),
        ("MY DUTY IS PREMATURELY DISCHARGED.",       "return (no value)"),
        ("SUMMON",                                   "function call"),
        ("WITH",                                     "function call arguments"),
        ("IF YOU PLEASE.",                           "end expression list"),
        ("A HIDEOUS CURSE ON",                       "throw"),
        ("WITH THE GREATEST RESPECT,",               "try block"),
        ("WITH GRATITUDE",                           "success handler"),
        ("MODIFIED RAPTURE",                         "exception handler"),
        ("THAT CONCLUDES THE MATTER.",               "end try/catch"),
        ("PRAY ADMIT",                               "import"),
        ("SUM OF",                                   "addition"),
        ("DIFFERENCE OF",                            "subtraction"),
        ("PRODUCT OF",                               "multiplication"),
        ("QUOTIENT OF",                              "division"),
        ("REMAINDER OF",                             "modulo"),
        ("LARGER OF",                                "maximum"),
        ("SMALLER OF",                               "minimum"),
        ("WOVEN OF",                                 "string concatenation"),
        ("BOTH",                                     "logical AND"),
        ("EITHER",                                   "logical OR"),
        ("HARDLY EVER",                              "logical NOT"),
        ("ALIKE",                                    "equality (==)"),
        ("UNLIKE",                                   "inequality (!=)"),
        ("PRE-ADAMITE",                              "greater than (>)"),
        ("LOWER DEGREE",                             "less than (<)"),
        ("ALL OF",                                   "all-true (variadic AND)"),
        ("ANY OF",                                   "any-true (variadic OR)"),
        ("VERITY",                                   "boolean true"),
        ("NAY",                                      "boolean false"),
        ("NAUGHT",                                   "null"),
        ("JUST SO",                                  "implicit variable"),
        ("PEER",                                     "integer type"),
        ("FATHOM",                                   "float type"),
        ("YARN",                                     "string type"),
        ("DECREE",                                   "boolean type"),
        ("A LITTLE LIST OF",                         "array type annotation"),
        ("VICTIM",                                   "array element access / assignment"),
        ("ON",                                       "array index separator"),
    ];
}
