using BWHazel.TopsyTurvy.UtopIR.Analysis;
using BWHazel.TopsyTurvy.UtopIR.Ast;
using BWHazel.TopsyTurvy.UtopIR.Parser;

namespace BWHazel.TopsyTurvy.UtopIR.Tests.Parser;

/// <summary>
/// Tests for the <see cref="UtopIRParser"/> class.
/// </summary>
public class UtopIRParserTests
{
    private readonly UtopIRParser parser = new();

    /// <summary>
    /// Tests that <see cref="UtopIRParser.TryParse"/> parses a worked example from into the expected instruction sequence.
    /// </summary>
    [Fact]
    public void TryParse_WithWorkedExample_ProducesExpectedInstructions()
    {
        const string source =
            """
            duty &Opera, finds peer
                £Peer1 = welcome peer
                £Peer1 = appoint 42
                £Peer2 = welcome peer
                £Peer2 = appoint 30
                £PeerResultA = welcome peer
                £_sum_Peer1_Peer2 = sum £Peer1, £Peer2
                £PeerResultA = appoint £_sum_Peer1_Peer2

                find £PeerResultA
            discharged
            """;

        UtopIRParseResult result = this.parser.TryParse(source);

        result.Success.ShouldBeTrue();
        result.Diagnostics.ShouldBeEmpty();
        result.Program!.Functions.Count.ShouldBe(1);
        UtopIRFunctionDefinition opera = result.Program.Functions[0];
        opera.Name.ShouldBe("Opera");
        opera.Body.Count.ShouldBe(8);
        opera.Body[0].ShouldBeOfType<WelcomeInstruction>().Target.Name.ShouldBe("Peer1");
        opera.Body[5].ShouldBeOfType<ArithmeticInstruction>().Target.Name.ShouldBe("_sum_Peer1_Peer2");
        FindInstruction find = opera.Body[7].ShouldBeOfType<FindInstruction>();
        find.Value.ShouldBeOfType<VariableOperand>().Variable.Name.ShouldBe("PeerResultA");
    }

    /// <summary>
    /// Tests that <see cref="UtopIRParser.TryParse"/> returns an empty function body for an <c>Opera</c> function with no instructions.
    /// </summary>
    [Fact]
    public void TryParse_WithEmptyFunctionBody_ReturnsEmptyBody()
    {
        UtopIRParseResult result = this.parser.TryParse("duty &Opera\ndischarged");

        result.Success.ShouldBeTrue();
        result.Program!.Functions.Count.ShouldBe(1);
        result.Program.Functions[0].Body.ShouldBeEmpty();
    }

    /// <summary>
    /// Tests that <see cref="UtopIRParser.TryParse"/> reports a diagnostic with the correct line for a malformed instruction.
    /// </summary>
    [Fact]
    public void TryParse_WithMalformedInstruction_ReportsDiagnosticAtCorrectLine()
    {
        const string source = "duty &Opera\n£a = welcome peer\n£a = bogus 5\ndischarged";

        UtopIRParseResult result = this.parser.TryParse(source);

        result.Success.ShouldBeFalse();
        result.Diagnostics.Count.ShouldBe(1);
        result.Diagnostics[0].Line.ShouldBe(3);
    }

    /// <summary>
    /// Tests that <see cref="UtopIRParser.Parse"/> throws <see cref="UtopIRSyntaxException"/> for invalid source.
    /// </summary>
    [Fact]
    public void Parse_WithInvalidSource_ThrowsUtopIRSyntaxException()
    {
        Should.Throw<UtopIRSyntaxException>(() => this.parser.Parse("£a = bogus 5"));
    }

    /// <summary>
    /// Tests that <see cref="UtopIRParser.Parse"/> returns the parsed programme for valid source.
    /// </summary>
    [Fact]
    public void Parse_WithValidSource_ReturnsProgramme()
    {
        UtopIRProgram program = this.parser.Parse("duty &Opera\n£a = welcome peer\n£a = appoint 5\nfind £a\ndischarged");

        program.Functions.Count.ShouldBe(1);
        program.Functions[0].Body.Count.ShouldBe(3);
    }

    /// <summary>
    /// Tests that UtopIR text generated by <see cref="UtopIRCodeGenerator"/> from a hand-built <see cref="UtopIRProgram"/> parses back to a structurally-equal programme.
    /// </summary>
    [Fact]
    public void TryParse_RoundTripsCodeGeneratorOutput()
    {
        UtopIRProgram original = new([
            new UtopIRFunctionDefinition(
                "Opera",
                [],
                new UtopIRTermType(UtopIRType.Peer),
                [
                    new WelcomeInstruction(new("a"), UtopIRType.Peer),
                    new AppointInstruction(new("a"), new LiteralOperand(10)),
                    new WelcomeInstruction(new("b"), UtopIRType.Chancellor),
                    new WereInstruction(new("b"), new VariableOperand(new("a")), UtopIRType.Chancellor),
                    new ArithmeticInstruction(UtopIRArithmeticOperation.Sum, new("r"), new VariableOperand(new("a")), new VariableOperand(new("b"))),
                    new PrenticeInstruction(new LiteralOperand(99)),
                    new LeaveInstruction(new("r")),
                    new SummonInstruction(new FunctionReference("PreviewBehold"), []),
                    new SummonFindInstruction(new("input"), new FunctionReference("PreviewPrayTell"), []),
                    new FindInstruction(new VariableOperand(new("r")))
                ])
        ]);

        string generated = new UtopIRCodeGenerator().Generate(original);
        UtopIRParseResult result = this.parser.TryParse(generated);

        result.Success.ShouldBeTrue();
        result.Program!.Functions.ShouldBe(original.Functions);
    }
}
