using BWHazel.TopsyTurvy.UtopIR.Analysis;
using BWHazel.TopsyTurvy.UtopIR.Ast;
using BWHazel.TopsyTurvy.UtopIR.Parser;

namespace BWHazel.TopsyTurvy.UtopIR.Tests.Parser;

/// <summary>
/// Tests for the <see cref="UtopIRParser"/> class.
/// </summary>
public class UtopIRParserTests
{
    private readonly UtopIRParser parser = new();

    /// <summary>
    /// Tests that <see cref="UtopIRParser.TryParse"/> parses a worked example from into the expected instruction sequence.
    /// </summary>
    [Fact]
    public void TryParse_WithWorkedExampleFromSpec_ProducesExpectedInstructions()
    {
        const string source =
            """
            £Peer1 = welcome peer
            £Peer1 = appoint 42
            £Peer2 = welcome peer
            £Peer2 = appoint 30
            £PeerResultA = welcome peer
            £_sum_Peer1_Peer2 = sum £Peer1, £Peer2
            £PeerResultA = appoint £_sum_Peer1_Peer2

            find £PeerResultA
            """;

        UtopIRParseResult result = this.parser.TryParse(source);

        result.Success.ShouldBeTrue();
        result.Diagnostics.ShouldBeEmpty();
        result.Program!.Instructions.Count.ShouldBe(8);
        result.Program.Instructions[0].ShouldBeOfType<WelcomeInstruction>().Target.Name.ShouldBe("Peer1");
        result.Program.Instructions[5].ShouldBeOfType<ArithmeticInstruction>().Target.Name.ShouldBe("_sum_Peer1_Peer2");
        FindInstruction find = result.Program.Instructions[7].ShouldBeOfType<FindInstruction>();
        find.Value.ShouldBeOfType<VariableOperand>().Variable.Name.ShouldBe("PeerResultA");
    }

    /// <summary>
    /// Tests that <see cref="UtopIRParser.TryParse"/> returns an empty programme for empty source text.
    /// </summary>
    [Fact]
    public void TryParse_WithEmptySource_ReturnsEmptyProgramme()
    {
        UtopIRParseResult result = this.parser.TryParse(string.Empty);

        result.Success.ShouldBeTrue();
        result.Program!.Instructions.ShouldBeEmpty();
    }

    /// <summary>
    /// Tests that <see cref="UtopIRParser.TryParse"/> reports a diagnostic with the correct line for a malformed instruction.
    /// </summary>
    [Fact]
    public void TryParse_WithMalformedInstruction_ReportsDiagnosticAtCorrectLine()
    {
        const string source = "£a = welcome peer\n£a = bogus 5";

        UtopIRParseResult result = this.parser.TryParse(source);

        result.Success.ShouldBeFalse();
        result.Diagnostics.Count.ShouldBe(1);
        result.Diagnostics[0].Line.ShouldBe(2);
    }

    /// <summary>
    /// Tests that <see cref="UtopIRParser.Parse"/> throws <see cref="UtopIRSyntaxException"/> for invalid source.
    /// </summary>
    [Fact]
    public void Parse_WithInvalidSource_ThrowsUtopIRSyntaxException()
    {
        Should.Throw<UtopIRSyntaxException>(() => this.parser.Parse("£a = bogus 5"));
    }

    /// <summary>
    /// Tests that <see cref="UtopIRParser.Parse"/> returns the parsed programme for valid source.
    /// </summary>
    [Fact]
    public void Parse_WithValidSource_ReturnsProgramme()
    {
        UtopIRProgram program = this.parser.Parse("£a = welcome peer\n£a = appoint 5\nfind £a");

        program.Instructions.Count.ShouldBe(3);
    }

    /// <summary>
    /// Tests that UtopIR text generated by <see cref="UtopIRCodeGenerator"/> from a hand-built <see cref="UtopIRProgram"/> parses back to a structurally-equal programme.
    /// </summary>
    [Fact]
    public void TryParse_RoundTripsCodeGeneratorOutput()
    {
        UtopIRProgram original = new([
            new WelcomeInstruction(new("a"), UtopIRType.Peer),
            new AppointInstruction(new("a"), new LiteralOperand(10)),
            new WelcomeInstruction(new("b"), UtopIRType.Chancellor),
            new WereInstruction(new("b"), new VariableOperand(new("a")), UtopIRType.Chancellor),
            new ArithmeticInstruction(UtopIRArithmeticOperation.Sum, new("r"), new VariableOperand(new("a")), new VariableOperand(new("b"))),
            new PrenticeInstruction(new LiteralOperand(99)),
            new LeaveInstruction(new("r")),
            new SummonInstruction(new FunctionReference("PreviewBehold")),
            new SummonFindInstruction(new("input"), new FunctionReference("PreviewPrayTell")),
            new FindInstruction(new VariableOperand(new("r")))
        ]);

        string generated = new UtopIRCodeGenerator().Generate(original);
        UtopIRParseResult result = this.parser.TryParse(generated);

        result.Success.ShouldBeTrue();
        result.Program!.Instructions.ShouldBe(original.Instructions);
    }
}
