namespace BWHazel.TopsyTurvy.Ast;

/// <summary>
/// Represents a diagnostic message generated by the parser or runtime.
/// </summary>
/// <remarks>
/// <para>
/// A <see cref="Diagnostic"/> is a structured report raised by language processors, such as the parser, runtime or language
/// server, during analysis of Topsy Turvy code to raise issues.  These can range from informational messages to warnings and
/// errors which can be semantic, syntax or runtime errors.  Each diagnostic is associated with a <see cref="Span"/> pinpointing
/// the source region that triggered it along with a human-readable <see cref="Message"/> and a <see cref="Severity"/> classifying
/// its importance.  It should be noted that a diagnostic is not necessarily an error.
/// </para>
/// <para>
/// Diagnostics are accumulated in a <see cref="DiagnosticCollection"/> and returned from parse and execution operations so
/// that callers can report them back to the user via interactive toolings such as the CLI or to the web editor.
/// </para>
/// <para>
/// There is no Topsy Turvy syntax that maps directly to <see cref="Diagnostic"/>.  It is an infrastructure
/// type used for diagnostic reporting and is never directly instantiated by user code.
/// </para>
/// </remarks>
/// <param name="Message">The descriptive message.</param>
/// <param name="Severity">The severity of the diagnostic.</param>
/// <param name="Span">The source code span associated with the diagnostic.</param>
public record Diagnostic(string Message, DiagnosticSeverity Severity, SourceSpan Span);
