namespace BWHazel.TopsyTurvy.Ast;

/// <summary>
/// Represents a diagnostic message generated by the parser or runtime.
/// </summary>
/// <param name="Message">The descriptive error message.</param>
/// <param name="Severity">The severity of the diagnostic.</param>
/// <param name="Span">The source code span associated with the diagnostic.</param>
public record TopsyTurvyDiagnostic(string Message, TopsyTurvyDiagnosticSeverity Severity, TopsyTurvySourceSpan Span);
